// Code generated by ent, DO NOT EDIT.

package checklist

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the checklist type in the database.
	Label = "checklist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldInspectionType holds the string denoting the inspection_type field in the database.
	FieldInspectionType = "inspection_type"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeElements holds the string denoting the elements edge name in mutations.
	EdgeElements = "elements"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// Table holds the table name of the checklist in the database.
	Table = "checklists"
	// ElementsTable is the table that holds the elements relation/edge.
	ElementsTable = "checklist_elements"
	// ElementsInverseTable is the table name for the ChecklistElement entity.
	// It exists in this package in order to avoid circular dependency with the "checklistelement" package.
	ElementsInverseTable = "checklist_elements"
	// ElementsColumn is the table column denoting the elements relation/edge.
	ElementsColumn = "checklist_id"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "tasks"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "checklist_id"
)

// Columns holds all SQL columns for checklist fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldInspectionType,
	FieldDescription,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// InspectionType defines the type for the "inspection_type" enum field.
type InspectionType string

// InspectionTypePartial is the default value of the InspectionType enum.
const DefaultInspectionType = InspectionTypePartial

// InspectionType values.
const (
	InspectionTypeSpring  InspectionType = "spring"
	InspectionTypeWinter  InspectionType = "winter"
	InspectionTypePartial InspectionType = "partial"
)

func (it InspectionType) String() string {
	return string(it)
}

// InspectionTypeValidator is a validator for the "inspection_type" field enum values. It is called by the builders before save.
func InspectionTypeValidator(it InspectionType) error {
	switch it {
	case InspectionTypeSpring, InspectionTypeWinter, InspectionTypePartial:
		return nil
	default:
		return fmt.Errorf("checklist: invalid enum value for inspection_type field: %q", it)
	}
}

// OrderOption defines the ordering options for the Checklist queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByInspectionType orders the results by the inspection_type field.
func ByInspectionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInspectionType, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByElementsCount orders the results by elements count.
func ByElementsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newElementsStep(), opts...)
	}
}

// ByElements orders the results by elements terms.
func ByElements(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newElementsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newElementsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ElementsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ElementsTable, ElementsColumn),
	)
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
	)
}
