// Code generated by ent, DO NOT EDIT.

package inspectorunit

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the inspectorunit type in the database.
	Label = "inspector_unit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldJkhUnitID holds the string denoting the jkh_unit_id field in the database.
	FieldJkhUnitID = "jkh_unit_id"
	// EdgeInspector holds the string denoting the inspector edge name in mutations.
	EdgeInspector = "inspector"
	// EdgeJkhUnit holds the string denoting the jkh_unit edge name in mutations.
	EdgeJkhUnit = "jkh_unit"
	// Table holds the table name of the inspectorunit in the database.
	Table = "inspector_units"
	// InspectorTable is the table that holds the inspector relation/edge.
	InspectorTable = "inspector_units"
	// InspectorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InspectorInverseTable = "users"
	// InspectorColumn is the table column denoting the inspector relation/edge.
	InspectorColumn = "user_id"
	// JkhUnitTable is the table that holds the jkh_unit relation/edge.
	JkhUnitTable = "inspector_units"
	// JkhUnitInverseTable is the table name for the JkhUnit entity.
	// It exists in this package in order to avoid circular dependency with the "jkhunit" package.
	JkhUnitInverseTable = "jkh_units"
	// JkhUnitColumn is the table column denoting the jkh_unit relation/edge.
	JkhUnitColumn = "jkh_unit_id"
)

// Columns holds all SQL columns for inspectorunit fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldJkhUnitID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the InspectorUnit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByJkhUnitID orders the results by the jkh_unit_id field.
func ByJkhUnitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJkhUnitID, opts...).ToFunc()
}

// ByInspectorField orders the results by inspector field.
func ByInspectorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInspectorStep(), sql.OrderByField(field, opts...))
	}
}

// ByJkhUnitField orders the results by jkh_unit field.
func ByJkhUnitField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJkhUnitStep(), sql.OrderByField(field, opts...))
	}
}
func newInspectorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InspectorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InspectorTable, InspectorColumn),
	)
}
func newJkhUnitStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JkhUnitInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, JkhUnitTable, JkhUnitColumn),
	)
}
