// Code generated by ent, DO NOT EDIT.

package jkhunit

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the jkhunit type in the database.
	Label = "jkh_unit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDistrictID holds the string denoting the district_id field in the database.
	FieldDistrictID = "district_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeDistrict holds the string denoting the district edge name in mutations.
	EdgeDistrict = "district"
	// EdgeBuildings holds the string denoting the buildings edge name in mutations.
	EdgeBuildings = "buildings"
	// EdgeAssignedInspectors holds the string denoting the assigned_inspectors edge name in mutations.
	EdgeAssignedInspectors = "assigned_inspectors"
	// Table holds the table name of the jkhunit in the database.
	Table = "jkh_units"
	// DistrictTable is the table that holds the district relation/edge.
	DistrictTable = "jkh_units"
	// DistrictInverseTable is the table name for the District entity.
	// It exists in this package in order to avoid circular dependency with the "district" package.
	DistrictInverseTable = "districts"
	// DistrictColumn is the table column denoting the district relation/edge.
	DistrictColumn = "district_id"
	// BuildingsTable is the table that holds the buildings relation/edge.
	BuildingsTable = "buildings"
	// BuildingsInverseTable is the table name for the Building entity.
	// It exists in this package in order to avoid circular dependency with the "building" package.
	BuildingsInverseTable = "buildings"
	// BuildingsColumn is the table column denoting the buildings relation/edge.
	BuildingsColumn = "jkh_unit_id"
	// AssignedInspectorsTable is the table that holds the assigned_inspectors relation/edge.
	AssignedInspectorsTable = "inspector_units"
	// AssignedInspectorsInverseTable is the table name for the InspectorUnit entity.
	// It exists in this package in order to avoid circular dependency with the "inspectorunit" package.
	AssignedInspectorsInverseTable = "inspector_units"
	// AssignedInspectorsColumn is the table column denoting the assigned_inspectors relation/edge.
	AssignedInspectorsColumn = "jkh_unit_id"
)

// Columns holds all SQL columns for jkhunit fields.
var Columns = []string{
	FieldID,
	FieldDistrictID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the JkhUnit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDistrictID orders the results by the district_id field.
func ByDistrictID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistrictID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDistrictField orders the results by district field.
func ByDistrictField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDistrictStep(), sql.OrderByField(field, opts...))
	}
}

// ByBuildingsCount orders the results by buildings count.
func ByBuildingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBuildingsStep(), opts...)
	}
}

// ByBuildings orders the results by buildings terms.
func ByBuildings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBuildingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAssignedInspectorsCount orders the results by assigned_inspectors count.
func ByAssignedInspectorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAssignedInspectorsStep(), opts...)
	}
}

// ByAssignedInspectors orders the results by assigned_inspectors terms.
func ByAssignedInspectors(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignedInspectorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDistrictStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DistrictInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DistrictTable, DistrictColumn),
	)
}
func newBuildingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BuildingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BuildingsTable, BuildingsColumn),
	)
}
func newAssignedInspectorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignedInspectorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AssignedInspectorsTable, AssignedInspectorsColumn),
	)
}
