// Code generated by ent, DO NOT EDIT.

package checklistelement

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the checklistelement type in the database.
	Label = "checklist_element"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChecklistID holds the string denoting the checklist_id field in the database.
	FieldChecklistID = "checklist_id"
	// FieldElementID holds the string denoting the element_id field in the database.
	FieldElementID = "element_id"
	// FieldOrderIndex holds the string denoting the order_index field in the database.
	FieldOrderIndex = "order_index"
	// EdgeChecklist holds the string denoting the checklist edge name in mutations.
	EdgeChecklist = "checklist"
	// EdgeElementCatalog holds the string denoting the element_catalog edge name in mutations.
	EdgeElementCatalog = "element_catalog"
	// EdgeInspectionResults holds the string denoting the inspection_results edge name in mutations.
	EdgeInspectionResults = "inspection_results"
	// Table holds the table name of the checklistelement in the database.
	Table = "checklist_elements"
	// ChecklistTable is the table that holds the checklist relation/edge.
	ChecklistTable = "checklist_elements"
	// ChecklistInverseTable is the table name for the Checklist entity.
	// It exists in this package in order to avoid circular dependency with the "checklist" package.
	ChecklistInverseTable = "checklists"
	// ChecklistColumn is the table column denoting the checklist relation/edge.
	ChecklistColumn = "checklist_id"
	// ElementCatalogTable is the table that holds the element_catalog relation/edge.
	ElementCatalogTable = "checklist_elements"
	// ElementCatalogInverseTable is the table name for the ElementCatalog entity.
	// It exists in this package in order to avoid circular dependency with the "elementcatalog" package.
	ElementCatalogInverseTable = "element_catalogs"
	// ElementCatalogColumn is the table column denoting the element_catalog relation/edge.
	ElementCatalogColumn = "element_id"
	// InspectionResultsTable is the table that holds the inspection_results relation/edge.
	InspectionResultsTable = "inspection_results"
	// InspectionResultsInverseTable is the table name for the InspectionResult entity.
	// It exists in this package in order to avoid circular dependency with the "inspectionresult" package.
	InspectionResultsInverseTable = "inspection_results"
	// InspectionResultsColumn is the table column denoting the inspection_results relation/edge.
	InspectionResultsColumn = "checklist_element_id"
)

// Columns holds all SQL columns for checklistelement fields.
var Columns = []string{
	FieldID,
	FieldChecklistID,
	FieldElementID,
	FieldOrderIndex,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ChecklistElement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChecklistID orders the results by the checklist_id field.
func ByChecklistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChecklistID, opts...).ToFunc()
}

// ByElementID orders the results by the element_id field.
func ByElementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldElementID, opts...).ToFunc()
}

// ByOrderIndex orders the results by the order_index field.
func ByOrderIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderIndex, opts...).ToFunc()
}

// ByChecklistField orders the results by checklist field.
func ByChecklistField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChecklistStep(), sql.OrderByField(field, opts...))
	}
}

// ByElementCatalogField orders the results by element_catalog field.
func ByElementCatalogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newElementCatalogStep(), sql.OrderByField(field, opts...))
	}
}

// ByInspectionResultsCount orders the results by inspection_results count.
func ByInspectionResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInspectionResultsStep(), opts...)
	}
}

// ByInspectionResults orders the results by inspection_results terms.
func ByInspectionResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInspectionResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChecklistStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChecklistInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChecklistTable, ChecklistColumn),
	)
}
func newElementCatalogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ElementCatalogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ElementCatalogTable, ElementCatalogColumn),
	)
}
func newInspectionResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InspectionResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InspectionResultsTable, InspectionResultsColumn),
	)
}
