// Code generated by ent, DO NOT EDIT.

package checklistelement

import (
	"jkh/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldLTE(FieldID, id))
}

// ChecklistID applies equality check predicate on the "checklist_id" field. It's identical to ChecklistIDEQ.
func ChecklistID(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldEQ(FieldChecklistID, v))
}

// ElementID applies equality check predicate on the "element_id" field. It's identical to ElementIDEQ.
func ElementID(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldEQ(FieldElementID, v))
}

// OrderIndex applies equality check predicate on the "order_index" field. It's identical to OrderIndexEQ.
func OrderIndex(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldEQ(FieldOrderIndex, v))
}

// ChecklistIDEQ applies the EQ predicate on the "checklist_id" field.
func ChecklistIDEQ(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldEQ(FieldChecklistID, v))
}

// ChecklistIDNEQ applies the NEQ predicate on the "checklist_id" field.
func ChecklistIDNEQ(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldNEQ(FieldChecklistID, v))
}

// ChecklistIDIn applies the In predicate on the "checklist_id" field.
func ChecklistIDIn(vs ...int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldIn(FieldChecklistID, vs...))
}

// ChecklistIDNotIn applies the NotIn predicate on the "checklist_id" field.
func ChecklistIDNotIn(vs ...int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldNotIn(FieldChecklistID, vs...))
}

// ElementIDEQ applies the EQ predicate on the "element_id" field.
func ElementIDEQ(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldEQ(FieldElementID, v))
}

// ElementIDNEQ applies the NEQ predicate on the "element_id" field.
func ElementIDNEQ(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldNEQ(FieldElementID, v))
}

// ElementIDIn applies the In predicate on the "element_id" field.
func ElementIDIn(vs ...int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldIn(FieldElementID, vs...))
}

// ElementIDNotIn applies the NotIn predicate on the "element_id" field.
func ElementIDNotIn(vs ...int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldNotIn(FieldElementID, vs...))
}

// OrderIndexEQ applies the EQ predicate on the "order_index" field.
func OrderIndexEQ(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldEQ(FieldOrderIndex, v))
}

// OrderIndexNEQ applies the NEQ predicate on the "order_index" field.
func OrderIndexNEQ(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldNEQ(FieldOrderIndex, v))
}

// OrderIndexIn applies the In predicate on the "order_index" field.
func OrderIndexIn(vs ...int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldIn(FieldOrderIndex, vs...))
}

// OrderIndexNotIn applies the NotIn predicate on the "order_index" field.
func OrderIndexNotIn(vs ...int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldNotIn(FieldOrderIndex, vs...))
}

// OrderIndexGT applies the GT predicate on the "order_index" field.
func OrderIndexGT(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldGT(FieldOrderIndex, v))
}

// OrderIndexGTE applies the GTE predicate on the "order_index" field.
func OrderIndexGTE(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldGTE(FieldOrderIndex, v))
}

// OrderIndexLT applies the LT predicate on the "order_index" field.
func OrderIndexLT(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldLT(FieldOrderIndex, v))
}

// OrderIndexLTE applies the LTE predicate on the "order_index" field.
func OrderIndexLTE(v int) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldLTE(FieldOrderIndex, v))
}

// OrderIndexIsNil applies the IsNil predicate on the "order_index" field.
func OrderIndexIsNil() predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldIsNull(FieldOrderIndex))
}

// OrderIndexNotNil applies the NotNil predicate on the "order_index" field.
func OrderIndexNotNil() predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.FieldNotNull(FieldOrderIndex))
}

// HasChecklist applies the HasEdge predicate on the "checklist" edge.
func HasChecklist() predicate.ChecklistElement {
	return predicate.ChecklistElement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChecklistTable, ChecklistColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChecklistWith applies the HasEdge predicate on the "checklist" edge with a given conditions (other predicates).
func HasChecklistWith(preds ...predicate.Checklist) predicate.ChecklistElement {
	return predicate.ChecklistElement(func(s *sql.Selector) {
		step := newChecklistStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasElementCatalog applies the HasEdge predicate on the "element_catalog" edge.
func HasElementCatalog() predicate.ChecklistElement {
	return predicate.ChecklistElement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ElementCatalogTable, ElementCatalogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasElementCatalogWith applies the HasEdge predicate on the "element_catalog" edge with a given conditions (other predicates).
func HasElementCatalogWith(preds ...predicate.ElementCatalog) predicate.ChecklistElement {
	return predicate.ChecklistElement(func(s *sql.Selector) {
		step := newElementCatalogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInspectionResults applies the HasEdge predicate on the "inspection_results" edge.
func HasInspectionResults() predicate.ChecklistElement {
	return predicate.ChecklistElement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InspectionResultsTable, InspectionResultsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInspectionResultsWith applies the HasEdge predicate on the "inspection_results" edge with a given conditions (other predicates).
func HasInspectionResultsWith(preds ...predicate.InspectionResult) predicate.ChecklistElement {
	return predicate.ChecklistElement(func(s *sql.Selector) {
		step := newInspectionResultsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChecklistElement) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChecklistElement) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChecklistElement) predicate.ChecklistElement {
	return predicate.ChecklistElement(sql.NotPredicates(p))
}
