// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BuildingsColumns holds the columns for the "buildings" table.
	BuildingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "address", Type: field.TypeString, Unique: true},
		{Name: "construction_year", Type: field.TypeInt, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "photo", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "district_id", Type: field.TypeInt},
		{Name: "jkh_unit_id", Type: field.TypeInt},
		{Name: "inspector_id", Type: field.TypeInt, Nullable: true},
	}
	// BuildingsTable holds the schema information for the "buildings" table.
	BuildingsTable = &schema.Table{
		Name:       "buildings",
		Columns:    BuildingsColumns,
		PrimaryKey: []*schema.Column{BuildingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "buildings_districts_buildings",
				Columns:    []*schema.Column{BuildingsColumns[5]},
				RefColumns: []*schema.Column{DistrictsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "buildings_jkh_units_buildings",
				Columns:    []*schema.Column{BuildingsColumns[6]},
				RefColumns: []*schema.Column{JkhUnitsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "buildings_users_assigned_buildings",
				Columns:    []*schema.Column{BuildingsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ChecklistsColumns holds the columns for the "checklists" table.
	ChecklistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true},
		{Name: "inspection_type", Type: field.TypeEnum, Enums: []string{"spring", "winter", "partial"}, Default: "partial"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ChecklistsTable holds the schema information for the "checklists" table.
	ChecklistsTable = &schema.Table{
		Name:       "checklists",
		Columns:    ChecklistsColumns,
		PrimaryKey: []*schema.Column{ChecklistsColumns[0]},
	}
	// ChecklistElementsColumns holds the columns for the "checklist_elements" table.
	ChecklistElementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_index", Type: field.TypeInt, Nullable: true},
		{Name: "checklist_id", Type: field.TypeInt},
		{Name: "element_id", Type: field.TypeInt},
	}
	// ChecklistElementsTable holds the schema information for the "checklist_elements" table.
	ChecklistElementsTable = &schema.Table{
		Name:       "checklist_elements",
		Columns:    ChecklistElementsColumns,
		PrimaryKey: []*schema.Column{ChecklistElementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "checklist_elements_checklists_elements",
				Columns:    []*schema.Column{ChecklistElementsColumns[2]},
				RefColumns: []*schema.Column{ChecklistsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "checklist_elements_element_catalogs_checklist_elements",
				Columns:    []*schema.Column{ChecklistElementsColumns[3]},
				RefColumns: []*schema.Column{ElementCatalogsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DistrictsColumns holds the columns for the "districts" table.
	DistrictsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// DistrictsTable holds the schema information for the "districts" table.
	DistrictsTable = &schema.Table{
		Name:       "districts",
		Columns:    DistrictsColumns,
		PrimaryKey: []*schema.Column{DistrictsColumns[0]},
	}
	// ElementCatalogsColumns holds the columns for the "element_catalogs" table.
	ElementCatalogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "category", Type: field.TypeString, Nullable: true},
	}
	// ElementCatalogsTable holds the schema information for the "element_catalogs" table.
	ElementCatalogsTable = &schema.Table{
		Name:       "element_catalogs",
		Columns:    ElementCatalogsColumns,
		PrimaryKey: []*schema.Column{ElementCatalogsColumns[0]},
	}
	// InspectionActsColumns holds the columns for the "inspection_acts" table.
	InspectionActsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "approved_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "создан"},
		{Name: "conclusion", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "document_path", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "task_id", Type: field.TypeInt, Unique: true},
	}
	// InspectionActsTable holds the schema information for the "inspection_acts" table.
	InspectionActsTable = &schema.Table{
		Name:       "inspection_acts",
		Columns:    InspectionActsColumns,
		PrimaryKey: []*schema.Column{InspectionActsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "inspection_acts_tasks_act",
				Columns:    []*schema.Column{InspectionActsColumns[6]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// InspectionResultsColumns holds the columns for the "inspection_results" table.
	InspectionResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "condition_status", Type: field.TypeEnum, Enums: []string{"Исправное", "Удовлетворительное", "Неудовлетворительное", "Аварийное"}},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "checklist_element_id", Type: field.TypeInt},
		{Name: "task_id", Type: field.TypeInt},
	}
	// InspectionResultsTable holds the schema information for the "inspection_results" table.
	InspectionResultsTable = &schema.Table{
		Name:       "inspection_results",
		Columns:    InspectionResultsColumns,
		PrimaryKey: []*schema.Column{InspectionResultsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "inspection_results_checklist_elements_inspection_results",
				Columns:    []*schema.Column{InspectionResultsColumns[5]},
				RefColumns: []*schema.Column{ChecklistElementsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "inspection_results_tasks_results",
				Columns:    []*schema.Column{InspectionResultsColumns[6]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// InspectorUnitsColumns holds the columns for the "inspector_units" table.
	InspectorUnitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "jkh_unit_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// InspectorUnitsTable holds the schema information for the "inspector_units" table.
	InspectorUnitsTable = &schema.Table{
		Name:       "inspector_units",
		Columns:    InspectorUnitsColumns,
		PrimaryKey: []*schema.Column{InspectorUnitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "inspector_units_jkh_units_assigned_inspectors",
				Columns:    []*schema.Column{InspectorUnitsColumns[1]},
				RefColumns: []*schema.Column{JkhUnitsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "inspector_units_users_assigned_units",
				Columns:    []*schema.Column{InspectorUnitsColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// JkhUnitsColumns holds the columns for the "jkh_units" table.
	JkhUnitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "district_id", Type: field.TypeInt},
	}
	// JkhUnitsTable holds the schema information for the "jkh_units" table.
	JkhUnitsTable = &schema.Table{
		Name:       "jkh_units",
		Columns:    JkhUnitsColumns,
		PrimaryKey: []*schema.Column{JkhUnitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "jkh_units_districts_jkh_units",
				Columns:    []*schema.Column{JkhUnitsColumns[2]},
				RefColumns: []*schema.Column{DistrictsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "priority", Type: field.TypeString, Default: "обычный"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"New", "Pending", "InProgress", "OnReview", "ForRevision", "Approved", "Canceled"}, Default: "New"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "scheduled_date", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "building_id", Type: field.TypeInt},
		{Name: "checklist_id", Type: field.TypeInt},
		{Name: "inspector_id", Type: field.TypeInt},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tasks_buildings_tasks",
				Columns:    []*schema.Column{TasksColumns[8]},
				RefColumns: []*schema.Column{BuildingsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tasks_checklists_tasks",
				Columns:    []*schema.Column{TasksColumns[9]},
				RefColumns: []*schema.Column{ChecklistsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tasks_users_inspections",
				Columns:    []*schema.Column{TasksColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "login", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "role_id", Type: field.TypeInt},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_roles_users",
				Columns:    []*schema.Column{UsersColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BuildingsTable,
		ChecklistsTable,
		ChecklistElementsTable,
		DistrictsTable,
		ElementCatalogsTable,
		InspectionActsTable,
		InspectionResultsTable,
		InspectorUnitsTable,
		JkhUnitsTable,
		RolesTable,
		TasksTable,
		UsersTable,
	}
)

func init() {
	BuildingsTable.ForeignKeys[0].RefTable = DistrictsTable
	BuildingsTable.ForeignKeys[1].RefTable = JkhUnitsTable
	BuildingsTable.ForeignKeys[2].RefTable = UsersTable
	ChecklistElementsTable.ForeignKeys[0].RefTable = ChecklistsTable
	ChecklistElementsTable.ForeignKeys[1].RefTable = ElementCatalogsTable
	InspectionActsTable.ForeignKeys[0].RefTable = TasksTable
	InspectionResultsTable.ForeignKeys[0].RefTable = ChecklistElementsTable
	InspectionResultsTable.ForeignKeys[1].RefTable = TasksTable
	InspectorUnitsTable.ForeignKeys[0].RefTable = JkhUnitsTable
	InspectorUnitsTable.ForeignKeys[1].RefTable = UsersTable
	JkhUnitsTable.ForeignKeys[0].RefTable = DistrictsTable
	TasksTable.ForeignKeys[0].RefTable = BuildingsTable
	TasksTable.ForeignKeys[1].RefTable = ChecklistsTable
	TasksTable.ForeignKeys[2].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = RolesTable
}
