// Code generated by ent, DO NOT EDIT.

package district

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the district type in the database.
	Label = "district"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeJkhUnits holds the string denoting the jkh_units edge name in mutations.
	EdgeJkhUnits = "jkh_units"
	// EdgeBuildings holds the string denoting the buildings edge name in mutations.
	EdgeBuildings = "buildings"
	// Table holds the table name of the district in the database.
	Table = "districts"
	// JkhUnitsTable is the table that holds the jkh_units relation/edge.
	JkhUnitsTable = "jkh_units"
	// JkhUnitsInverseTable is the table name for the JkhUnit entity.
	// It exists in this package in order to avoid circular dependency with the "jkhunit" package.
	JkhUnitsInverseTable = "jkh_units"
	// JkhUnitsColumn is the table column denoting the jkh_units relation/edge.
	JkhUnitsColumn = "district_id"
	// BuildingsTable is the table that holds the buildings relation/edge.
	BuildingsTable = "buildings"
	// BuildingsInverseTable is the table name for the Building entity.
	// It exists in this package in order to avoid circular dependency with the "building" package.
	BuildingsInverseTable = "buildings"
	// BuildingsColumn is the table column denoting the buildings relation/edge.
	BuildingsColumn = "district_id"
)

// Columns holds all SQL columns for district fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the District queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByJkhUnitsCount orders the results by jkh_units count.
func ByJkhUnitsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJkhUnitsStep(), opts...)
	}
}

// ByJkhUnits orders the results by jkh_units terms.
func ByJkhUnits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJkhUnitsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBuildingsCount orders the results by buildings count.
func ByBuildingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBuildingsStep(), opts...)
	}
}

// ByBuildings orders the results by buildings terms.
func ByBuildings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBuildingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newJkhUnitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JkhUnitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JkhUnitsTable, JkhUnitsColumn),
	)
}
func newBuildingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BuildingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BuildingsTable, BuildingsColumn),
	)
}
