// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"jkh/ent/building"
	"jkh/ent/district"
	"jkh/ent/jkhunit"
	"jkh/ent/predicate"
	"jkh/ent/task"
	"jkh/ent/user"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BuildingQuery is the builder for querying Building entities.
type BuildingQuery struct {
	config
	ctx           *QueryContext
	order         []building.OrderOption
	inters        []Interceptor
	predicates    []predicate.Building
	withJkhUnit   *JkhUnitQuery
	withDistrict  *DistrictQuery
	withInspector *UserQuery
	withTasks     *TaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BuildingQuery builder.
func (_q *BuildingQuery) Where(ps ...predicate.Building) *BuildingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BuildingQuery) Limit(limit int) *BuildingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BuildingQuery) Offset(offset int) *BuildingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BuildingQuery) Unique(unique bool) *BuildingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BuildingQuery) Order(o ...building.OrderOption) *BuildingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryJkhUnit chains the current query on the "jkh_unit" edge.
func (_q *BuildingQuery) QueryJkhUnit() *JkhUnitQuery {
	query := (&JkhUnitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(building.Table, building.FieldID, selector),
			sqlgraph.To(jkhunit.Table, jkhunit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, building.JkhUnitTable, building.JkhUnitColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDistrict chains the current query on the "district" edge.
func (_q *BuildingQuery) QueryDistrict() *DistrictQuery {
	query := (&DistrictClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(building.Table, building.FieldID, selector),
			sqlgraph.To(district.Table, district.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, building.DistrictTable, building.DistrictColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInspector chains the current query on the "inspector" edge.
func (_q *BuildingQuery) QueryInspector() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(building.Table, building.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, building.InspectorTable, building.InspectorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTasks chains the current query on the "tasks" edge.
func (_q *BuildingQuery) QueryTasks() *TaskQuery {
	query := (&TaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(building.Table, building.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, building.TasksTable, building.TasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Building entity from the query.
// Returns a *NotFoundError when no Building was found.
func (_q *BuildingQuery) First(ctx context.Context) (*Building, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{building.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BuildingQuery) FirstX(ctx context.Context) *Building {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Building ID from the query.
// Returns a *NotFoundError when no Building ID was found.
func (_q *BuildingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{building.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BuildingQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Building entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Building entity is found.
// Returns a *NotFoundError when no Building entities are found.
func (_q *BuildingQuery) Only(ctx context.Context) (*Building, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{building.Label}
	default:
		return nil, &NotSingularError{building.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BuildingQuery) OnlyX(ctx context.Context) *Building {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Building ID in the query.
// Returns a *NotSingularError when more than one Building ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BuildingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{building.Label}
	default:
		err = &NotSingularError{building.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BuildingQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Buildings.
func (_q *BuildingQuery) All(ctx context.Context) ([]*Building, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Building, *BuildingQuery]()
	return withInterceptors[[]*Building](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BuildingQuery) AllX(ctx context.Context) []*Building {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Building IDs.
func (_q *BuildingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(building.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BuildingQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BuildingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BuildingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BuildingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BuildingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BuildingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BuildingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BuildingQuery) Clone() *BuildingQuery {
	if _q == nil {
		return nil
	}
	return &BuildingQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]building.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Building{}, _q.predicates...),
		withJkhUnit:   _q.withJkhUnit.Clone(),
		withDistrict:  _q.withDistrict.Clone(),
		withInspector: _q.withInspector.Clone(),
		withTasks:     _q.withTasks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithJkhUnit tells the query-builder to eager-load the nodes that are connected to
// the "jkh_unit" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BuildingQuery) WithJkhUnit(opts ...func(*JkhUnitQuery)) *BuildingQuery {
	query := (&JkhUnitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withJkhUnit = query
	return _q
}

// WithDistrict tells the query-builder to eager-load the nodes that are connected to
// the "district" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BuildingQuery) WithDistrict(opts ...func(*DistrictQuery)) *BuildingQuery {
	query := (&DistrictClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDistrict = query
	return _q
}

// WithInspector tells the query-builder to eager-load the nodes that are connected to
// the "inspector" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BuildingQuery) WithInspector(opts ...func(*UserQuery)) *BuildingQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInspector = query
	return _q
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BuildingQuery) WithTasks(opts ...func(*TaskQuery)) *BuildingQuery {
	query := (&TaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTasks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DistrictID int `json:"district_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Building.Query().
//		GroupBy(building.FieldDistrictID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BuildingQuery) GroupBy(field string, fields ...string) *BuildingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BuildingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = building.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DistrictID int `json:"district_id,omitempty"`
//	}
//
//	client.Building.Query().
//		Select(building.FieldDistrictID).
//		Scan(ctx, &v)
func (_q *BuildingQuery) Select(fields ...string) *BuildingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BuildingSelect{BuildingQuery: _q}
	sbuild.label = building.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BuildingSelect configured with the given aggregations.
func (_q *BuildingQuery) Aggregate(fns ...AggregateFunc) *BuildingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BuildingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !building.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BuildingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Building, error) {
	var (
		nodes       = []*Building{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withJkhUnit != nil,
			_q.withDistrict != nil,
			_q.withInspector != nil,
			_q.withTasks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Building).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Building{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withJkhUnit; query != nil {
		if err := _q.loadJkhUnit(ctx, query, nodes, nil,
			func(n *Building, e *JkhUnit) { n.Edges.JkhUnit = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDistrict; query != nil {
		if err := _q.loadDistrict(ctx, query, nodes, nil,
			func(n *Building, e *District) { n.Edges.District = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withInspector; query != nil {
		if err := _q.loadInspector(ctx, query, nodes, nil,
			func(n *Building, e *User) { n.Edges.Inspector = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTasks; query != nil {
		if err := _q.loadTasks(ctx, query, nodes,
			func(n *Building) { n.Edges.Tasks = []*Task{} },
			func(n *Building, e *Task) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BuildingQuery) loadJkhUnit(ctx context.Context, query *JkhUnitQuery, nodes []*Building, init func(*Building), assign func(*Building, *JkhUnit)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Building)
	for i := range nodes {
		fk := nodes[i].JkhUnitID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(jkhunit.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "jkh_unit_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *BuildingQuery) loadDistrict(ctx context.Context, query *DistrictQuery, nodes []*Building, init func(*Building), assign func(*Building, *District)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Building)
	for i := range nodes {
		fk := nodes[i].DistrictID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(district.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "district_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *BuildingQuery) loadInspector(ctx context.Context, query *UserQuery, nodes []*Building, init func(*Building), assign func(*Building, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Building)
	for i := range nodes {
		fk := nodes[i].InspectorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "inspector_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *BuildingQuery) loadTasks(ctx context.Context, query *TaskQuery, nodes []*Building, init func(*Building), assign func(*Building, *Task)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Building)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(task.FieldBuildingID)
	}
	query.Where(predicate.Task(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(building.TasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BuildingID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "building_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *BuildingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BuildingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(building.Table, building.Columns, sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, building.FieldID)
		for i := range fields {
			if fields[i] != building.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withJkhUnit != nil {
			_spec.Node.AddColumnOnce(building.FieldJkhUnitID)
		}
		if _q.withDistrict != nil {
			_spec.Node.AddColumnOnce(building.FieldDistrictID)
		}
		if _q.withInspector != nil {
			_spec.Node.AddColumnOnce(building.FieldInspectorID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BuildingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(building.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = building.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BuildingGroupBy is the group-by builder for Building entities.
type BuildingGroupBy struct {
	selector
	build *BuildingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BuildingGroupBy) Aggregate(fns ...AggregateFunc) *BuildingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BuildingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BuildingQuery, *BuildingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BuildingGroupBy) sqlScan(ctx context.Context, root *BuildingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BuildingSelect is the builder for selecting fields of Building entities.
type BuildingSelect struct {
	*BuildingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BuildingSelect) Aggregate(fns ...AggregateFunc) *BuildingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BuildingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BuildingQuery, *BuildingSelect](ctx, _s.BuildingQuery, _s, _s.inters, v)
}

func (_s *BuildingSelect) sqlScan(ctx context.Context, root *BuildingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
