// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/checklist"
	"jkh/ent/checklistelement"
	"jkh/ent/elementcatalog"
	"jkh/ent/inspectionresult"
	"jkh/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChecklistElementUpdate is the builder for updating ChecklistElement entities.
type ChecklistElementUpdate struct {
	config
	hooks    []Hook
	mutation *ChecklistElementMutation
}

// Where appends a list predicates to the ChecklistElementUpdate builder.
func (_u *ChecklistElementUpdate) Where(ps ...predicate.ChecklistElement) *ChecklistElementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChecklistID sets the "checklist_id" field.
func (_u *ChecklistElementUpdate) SetChecklistID(v int) *ChecklistElementUpdate {
	_u.mutation.SetChecklistID(v)
	return _u
}

// SetNillableChecklistID sets the "checklist_id" field if the given value is not nil.
func (_u *ChecklistElementUpdate) SetNillableChecklistID(v *int) *ChecklistElementUpdate {
	if v != nil {
		_u.SetChecklistID(*v)
	}
	return _u
}

// SetElementID sets the "element_id" field.
func (_u *ChecklistElementUpdate) SetElementID(v int) *ChecklistElementUpdate {
	_u.mutation.SetElementID(v)
	return _u
}

// SetNillableElementID sets the "element_id" field if the given value is not nil.
func (_u *ChecklistElementUpdate) SetNillableElementID(v *int) *ChecklistElementUpdate {
	if v != nil {
		_u.SetElementID(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *ChecklistElementUpdate) SetOrderIndex(v int) *ChecklistElementUpdate {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *ChecklistElementUpdate) SetNillableOrderIndex(v *int) *ChecklistElementUpdate {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *ChecklistElementUpdate) AddOrderIndex(v int) *ChecklistElementUpdate {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// ClearOrderIndex clears the value of the "order_index" field.
func (_u *ChecklistElementUpdate) ClearOrderIndex() *ChecklistElementUpdate {
	_u.mutation.ClearOrderIndex()
	return _u
}

// SetChecklist sets the "checklist" edge to the Checklist entity.
func (_u *ChecklistElementUpdate) SetChecklist(v *Checklist) *ChecklistElementUpdate {
	return _u.SetChecklistID(v.ID)
}

// SetElementCatalogID sets the "element_catalog" edge to the ElementCatalog entity by ID.
func (_u *ChecklistElementUpdate) SetElementCatalogID(id int) *ChecklistElementUpdate {
	_u.mutation.SetElementCatalogID(id)
	return _u
}

// SetElementCatalog sets the "element_catalog" edge to the ElementCatalog entity.
func (_u *ChecklistElementUpdate) SetElementCatalog(v *ElementCatalog) *ChecklistElementUpdate {
	return _u.SetElementCatalogID(v.ID)
}

// AddInspectionResultIDs adds the "inspection_results" edge to the InspectionResult entity by IDs.
func (_u *ChecklistElementUpdate) AddInspectionResultIDs(ids ...int) *ChecklistElementUpdate {
	_u.mutation.AddInspectionResultIDs(ids...)
	return _u
}

// AddInspectionResults adds the "inspection_results" edges to the InspectionResult entity.
func (_u *ChecklistElementUpdate) AddInspectionResults(v ...*InspectionResult) *ChecklistElementUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInspectionResultIDs(ids...)
}

// Mutation returns the ChecklistElementMutation object of the builder.
func (_u *ChecklistElementUpdate) Mutation() *ChecklistElementMutation {
	return _u.mutation
}

// ClearChecklist clears the "checklist" edge to the Checklist entity.
func (_u *ChecklistElementUpdate) ClearChecklist() *ChecklistElementUpdate {
	_u.mutation.ClearChecklist()
	return _u
}

// ClearElementCatalog clears the "element_catalog" edge to the ElementCatalog entity.
func (_u *ChecklistElementUpdate) ClearElementCatalog() *ChecklistElementUpdate {
	_u.mutation.ClearElementCatalog()
	return _u
}

// ClearInspectionResults clears all "inspection_results" edges to the InspectionResult entity.
func (_u *ChecklistElementUpdate) ClearInspectionResults() *ChecklistElementUpdate {
	_u.mutation.ClearInspectionResults()
	return _u
}

// RemoveInspectionResultIDs removes the "inspection_results" edge to InspectionResult entities by IDs.
func (_u *ChecklistElementUpdate) RemoveInspectionResultIDs(ids ...int) *ChecklistElementUpdate {
	_u.mutation.RemoveInspectionResultIDs(ids...)
	return _u
}

// RemoveInspectionResults removes "inspection_results" edges to InspectionResult entities.
func (_u *ChecklistElementUpdate) RemoveInspectionResults(v ...*InspectionResult) *ChecklistElementUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInspectionResultIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChecklistElementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChecklistElementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChecklistElementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChecklistElementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChecklistElementUpdate) check() error {
	if _u.mutation.ChecklistCleared() && len(_u.mutation.ChecklistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChecklistElement.checklist"`)
	}
	if _u.mutation.ElementCatalogCleared() && len(_u.mutation.ElementCatalogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChecklistElement.element_catalog"`)
	}
	return nil
}

func (_u *ChecklistElementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checklistelement.Table, checklistelement.Columns, sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(checklistelement.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(checklistelement.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.OrderIndexCleared() {
		_spec.ClearField(checklistelement.FieldOrderIndex, field.TypeInt)
	}
	if _u.mutation.ChecklistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ChecklistTable,
			Columns: []string{checklistelement.ChecklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ChecklistTable,
			Columns: []string{checklistelement.ChecklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ElementCatalogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ElementCatalogTable,
			Columns: []string{checklistelement.ElementCatalogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elementcatalog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ElementCatalogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ElementCatalogTable,
			Columns: []string{checklistelement.ElementCatalogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elementcatalog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InspectionResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   checklistelement.InspectionResultsTable,
			Columns: []string{checklistelement.InspectionResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInspectionResultsIDs(); len(nodes) > 0 && !_u.mutation.InspectionResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   checklistelement.InspectionResultsTable,
			Columns: []string{checklistelement.InspectionResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InspectionResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   checklistelement.InspectionResultsTable,
			Columns: []string{checklistelement.InspectionResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checklistelement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChecklistElementUpdateOne is the builder for updating a single ChecklistElement entity.
type ChecklistElementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChecklistElementMutation
}

// SetChecklistID sets the "checklist_id" field.
func (_u *ChecklistElementUpdateOne) SetChecklistID(v int) *ChecklistElementUpdateOne {
	_u.mutation.SetChecklistID(v)
	return _u
}

// SetNillableChecklistID sets the "checklist_id" field if the given value is not nil.
func (_u *ChecklistElementUpdateOne) SetNillableChecklistID(v *int) *ChecklistElementUpdateOne {
	if v != nil {
		_u.SetChecklistID(*v)
	}
	return _u
}

// SetElementID sets the "element_id" field.
func (_u *ChecklistElementUpdateOne) SetElementID(v int) *ChecklistElementUpdateOne {
	_u.mutation.SetElementID(v)
	return _u
}

// SetNillableElementID sets the "element_id" field if the given value is not nil.
func (_u *ChecklistElementUpdateOne) SetNillableElementID(v *int) *ChecklistElementUpdateOne {
	if v != nil {
		_u.SetElementID(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *ChecklistElementUpdateOne) SetOrderIndex(v int) *ChecklistElementUpdateOne {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *ChecklistElementUpdateOne) SetNillableOrderIndex(v *int) *ChecklistElementUpdateOne {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *ChecklistElementUpdateOne) AddOrderIndex(v int) *ChecklistElementUpdateOne {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// ClearOrderIndex clears the value of the "order_index" field.
func (_u *ChecklistElementUpdateOne) ClearOrderIndex() *ChecklistElementUpdateOne {
	_u.mutation.ClearOrderIndex()
	return _u
}

// SetChecklist sets the "checklist" edge to the Checklist entity.
func (_u *ChecklistElementUpdateOne) SetChecklist(v *Checklist) *ChecklistElementUpdateOne {
	return _u.SetChecklistID(v.ID)
}

// SetElementCatalogID sets the "element_catalog" edge to the ElementCatalog entity by ID.
func (_u *ChecklistElementUpdateOne) SetElementCatalogID(id int) *ChecklistElementUpdateOne {
	_u.mutation.SetElementCatalogID(id)
	return _u
}

// SetElementCatalog sets the "element_catalog" edge to the ElementCatalog entity.
func (_u *ChecklistElementUpdateOne) SetElementCatalog(v *ElementCatalog) *ChecklistElementUpdateOne {
	return _u.SetElementCatalogID(v.ID)
}

// AddInspectionResultIDs adds the "inspection_results" edge to the InspectionResult entity by IDs.
func (_u *ChecklistElementUpdateOne) AddInspectionResultIDs(ids ...int) *ChecklistElementUpdateOne {
	_u.mutation.AddInspectionResultIDs(ids...)
	return _u
}

// AddInspectionResults adds the "inspection_results" edges to the InspectionResult entity.
func (_u *ChecklistElementUpdateOne) AddInspectionResults(v ...*InspectionResult) *ChecklistElementUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInspectionResultIDs(ids...)
}

// Mutation returns the ChecklistElementMutation object of the builder.
func (_u *ChecklistElementUpdateOne) Mutation() *ChecklistElementMutation {
	return _u.mutation
}

// ClearChecklist clears the "checklist" edge to the Checklist entity.
func (_u *ChecklistElementUpdateOne) ClearChecklist() *ChecklistElementUpdateOne {
	_u.mutation.ClearChecklist()
	return _u
}

// ClearElementCatalog clears the "element_catalog" edge to the ElementCatalog entity.
func (_u *ChecklistElementUpdateOne) ClearElementCatalog() *ChecklistElementUpdateOne {
	_u.mutation.ClearElementCatalog()
	return _u
}

// ClearInspectionResults clears all "inspection_results" edges to the InspectionResult entity.
func (_u *ChecklistElementUpdateOne) ClearInspectionResults() *ChecklistElementUpdateOne {
	_u.mutation.ClearInspectionResults()
	return _u
}

// RemoveInspectionResultIDs removes the "inspection_results" edge to InspectionResult entities by IDs.
func (_u *ChecklistElementUpdateOne) RemoveInspectionResultIDs(ids ...int) *ChecklistElementUpdateOne {
	_u.mutation.RemoveInspectionResultIDs(ids...)
	return _u
}

// RemoveInspectionResults removes "inspection_results" edges to InspectionResult entities.
func (_u *ChecklistElementUpdateOne) RemoveInspectionResults(v ...*InspectionResult) *ChecklistElementUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInspectionResultIDs(ids...)
}

// Where appends a list predicates to the ChecklistElementUpdate builder.
func (_u *ChecklistElementUpdateOne) Where(ps ...predicate.ChecklistElement) *ChecklistElementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChecklistElementUpdateOne) Select(field string, fields ...string) *ChecklistElementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChecklistElement entity.
func (_u *ChecklistElementUpdateOne) Save(ctx context.Context) (*ChecklistElement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChecklistElementUpdateOne) SaveX(ctx context.Context) *ChecklistElement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChecklistElementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChecklistElementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChecklistElementUpdateOne) check() error {
	if _u.mutation.ChecklistCleared() && len(_u.mutation.ChecklistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChecklistElement.checklist"`)
	}
	if _u.mutation.ElementCatalogCleared() && len(_u.mutation.ElementCatalogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChecklistElement.element_catalog"`)
	}
	return nil
}

func (_u *ChecklistElementUpdateOne) sqlSave(ctx context.Context) (_node *ChecklistElement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checklistelement.Table, checklistelement.Columns, sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChecklistElement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checklistelement.FieldID)
		for _, f := range fields {
			if !checklistelement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checklistelement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(checklistelement.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(checklistelement.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.OrderIndexCleared() {
		_spec.ClearField(checklistelement.FieldOrderIndex, field.TypeInt)
	}
	if _u.mutation.ChecklistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ChecklistTable,
			Columns: []string{checklistelement.ChecklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ChecklistTable,
			Columns: []string{checklistelement.ChecklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ElementCatalogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ElementCatalogTable,
			Columns: []string{checklistelement.ElementCatalogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elementcatalog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ElementCatalogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ElementCatalogTable,
			Columns: []string{checklistelement.ElementCatalogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elementcatalog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InspectionResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   checklistelement.InspectionResultsTable,
			Columns: []string{checklistelement.InspectionResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInspectionResultsIDs(); len(nodes) > 0 && !_u.mutation.InspectionResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   checklistelement.InspectionResultsTable,
			Columns: []string{checklistelement.InspectionResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InspectionResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   checklistelement.InspectionResultsTable,
			Columns: []string{checklistelement.InspectionResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChecklistElement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checklistelement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
