// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/checklist"
	"jkh/ent/checklistelement"
	"jkh/ent/elementcatalog"
	"jkh/ent/inspectionresult"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChecklistElementCreate is the builder for creating a ChecklistElement entity.
type ChecklistElementCreate struct {
	config
	mutation *ChecklistElementMutation
	hooks    []Hook
}

// SetChecklistID sets the "checklist_id" field.
func (_c *ChecklistElementCreate) SetChecklistID(v int) *ChecklistElementCreate {
	_c.mutation.SetChecklistID(v)
	return _c
}

// SetElementID sets the "element_id" field.
func (_c *ChecklistElementCreate) SetElementID(v int) *ChecklistElementCreate {
	_c.mutation.SetElementID(v)
	return _c
}

// SetOrderIndex sets the "order_index" field.
func (_c *ChecklistElementCreate) SetOrderIndex(v int) *ChecklistElementCreate {
	_c.mutation.SetOrderIndex(v)
	return _c
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_c *ChecklistElementCreate) SetNillableOrderIndex(v *int) *ChecklistElementCreate {
	if v != nil {
		_c.SetOrderIndex(*v)
	}
	return _c
}

// SetChecklist sets the "checklist" edge to the Checklist entity.
func (_c *ChecklistElementCreate) SetChecklist(v *Checklist) *ChecklistElementCreate {
	return _c.SetChecklistID(v.ID)
}

// SetElementCatalogID sets the "element_catalog" edge to the ElementCatalog entity by ID.
func (_c *ChecklistElementCreate) SetElementCatalogID(id int) *ChecklistElementCreate {
	_c.mutation.SetElementCatalogID(id)
	return _c
}

// SetElementCatalog sets the "element_catalog" edge to the ElementCatalog entity.
func (_c *ChecklistElementCreate) SetElementCatalog(v *ElementCatalog) *ChecklistElementCreate {
	return _c.SetElementCatalogID(v.ID)
}

// AddInspectionResultIDs adds the "inspection_results" edge to the InspectionResult entity by IDs.
func (_c *ChecklistElementCreate) AddInspectionResultIDs(ids ...int) *ChecklistElementCreate {
	_c.mutation.AddInspectionResultIDs(ids...)
	return _c
}

// AddInspectionResults adds the "inspection_results" edges to the InspectionResult entity.
func (_c *ChecklistElementCreate) AddInspectionResults(v ...*InspectionResult) *ChecklistElementCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInspectionResultIDs(ids...)
}

// Mutation returns the ChecklistElementMutation object of the builder.
func (_c *ChecklistElementCreate) Mutation() *ChecklistElementMutation {
	return _c.mutation
}

// Save creates the ChecklistElement in the database.
func (_c *ChecklistElementCreate) Save(ctx context.Context) (*ChecklistElement, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChecklistElementCreate) SaveX(ctx context.Context) *ChecklistElement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChecklistElementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChecklistElementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChecklistElementCreate) check() error {
	if _, ok := _c.mutation.ChecklistID(); !ok {
		return &ValidationError{Name: "checklist_id", err: errors.New(`ent: missing required field "ChecklistElement.checklist_id"`)}
	}
	if _, ok := _c.mutation.ElementID(); !ok {
		return &ValidationError{Name: "element_id", err: errors.New(`ent: missing required field "ChecklistElement.element_id"`)}
	}
	if len(_c.mutation.ChecklistIDs()) == 0 {
		return &ValidationError{Name: "checklist", err: errors.New(`ent: missing required edge "ChecklistElement.checklist"`)}
	}
	if len(_c.mutation.ElementCatalogIDs()) == 0 {
		return &ValidationError{Name: "element_catalog", err: errors.New(`ent: missing required edge "ChecklistElement.element_catalog"`)}
	}
	return nil
}

func (_c *ChecklistElementCreate) sqlSave(ctx context.Context) (*ChecklistElement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChecklistElementCreate) createSpec() (*ChecklistElement, *sqlgraph.CreateSpec) {
	var (
		_node = &ChecklistElement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checklistelement.Table, sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.OrderIndex(); ok {
		_spec.SetField(checklistelement.FieldOrderIndex, field.TypeInt, value)
		_node.OrderIndex = value
	}
	if nodes := _c.mutation.ChecklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ChecklistTable,
			Columns: []string{checklistelement.ChecklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChecklistID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ElementCatalogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checklistelement.ElementCatalogTable,
			Columns: []string{checklistelement.ElementCatalogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(elementcatalog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ElementID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InspectionResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   checklistelement.InspectionResultsTable,
			Columns: []string{checklistelement.InspectionResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChecklistElementCreateBulk is the builder for creating many ChecklistElement entities in bulk.
type ChecklistElementCreateBulk struct {
	config
	err      error
	builders []*ChecklistElementCreate
}

// Save creates the ChecklistElement entities in the database.
func (_c *ChecklistElementCreateBulk) Save(ctx context.Context) ([]*ChecklistElement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChecklistElement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChecklistElementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChecklistElementCreateBulk) SaveX(ctx context.Context) []*ChecklistElement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChecklistElementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChecklistElementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
