// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/checklist"
	"jkh/ent/checklistelement"
	"jkh/ent/task"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChecklistCreate is the builder for creating a Checklist entity.
type ChecklistCreate struct {
	config
	mutation *ChecklistMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ChecklistCreate) SetTitle(v string) *ChecklistCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetInspectionType sets the "inspection_type" field.
func (_c *ChecklistCreate) SetInspectionType(v checklist.InspectionType) *ChecklistCreate {
	_c.mutation.SetInspectionType(v)
	return _c
}

// SetNillableInspectionType sets the "inspection_type" field if the given value is not nil.
func (_c *ChecklistCreate) SetNillableInspectionType(v *checklist.InspectionType) *ChecklistCreate {
	if v != nil {
		_c.SetInspectionType(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ChecklistCreate) SetDescription(v string) *ChecklistCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ChecklistCreate) SetNillableDescription(v *string) *ChecklistCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChecklistCreate) SetCreatedAt(v time.Time) *ChecklistCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChecklistCreate) SetNillableCreatedAt(v *time.Time) *ChecklistCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// AddElementIDs adds the "elements" edge to the ChecklistElement entity by IDs.
func (_c *ChecklistCreate) AddElementIDs(ids ...int) *ChecklistCreate {
	_c.mutation.AddElementIDs(ids...)
	return _c
}

// AddElements adds the "elements" edges to the ChecklistElement entity.
func (_c *ChecklistCreate) AddElements(v ...*ChecklistElement) *ChecklistCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddElementIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_c *ChecklistCreate) AddTaskIDs(ids ...int) *ChecklistCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_c *ChecklistCreate) AddTasks(v ...*Task) *ChecklistCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// Mutation returns the ChecklistMutation object of the builder.
func (_c *ChecklistCreate) Mutation() *ChecklistMutation {
	return _c.mutation
}

// Save creates the Checklist in the database.
func (_c *ChecklistCreate) Save(ctx context.Context) (*Checklist, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChecklistCreate) SaveX(ctx context.Context) *Checklist {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChecklistCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChecklistCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChecklistCreate) defaults() {
	if _, ok := _c.mutation.InspectionType(); !ok {
		v := checklist.DefaultInspectionType
		_c.mutation.SetInspectionType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := checklist.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChecklistCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Checklist.title"`)}
	}
	if _, ok := _c.mutation.InspectionType(); !ok {
		return &ValidationError{Name: "inspection_type", err: errors.New(`ent: missing required field "Checklist.inspection_type"`)}
	}
	if v, ok := _c.mutation.InspectionType(); ok {
		if err := checklist.InspectionTypeValidator(v); err != nil {
			return &ValidationError{Name: "inspection_type", err: fmt.Errorf(`ent: validator failed for field "Checklist.inspection_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Checklist.created_at"`)}
	}
	return nil
}

func (_c *ChecklistCreate) sqlSave(ctx context.Context) (*Checklist, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChecklistCreate) createSpec() (*Checklist, *sqlgraph.CreateSpec) {
	var (
		_node = &Checklist{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checklist.Table, sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(checklist.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.InspectionType(); ok {
		_spec.SetField(checklist.FieldInspectionType, field.TypeEnum, value)
		_node.InspectionType = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(checklist.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(checklist.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ElementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   checklist.ElementsTable,
			Columns: []string{checklist.ElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   checklist.TasksTable,
			Columns: []string{checklist.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChecklistCreateBulk is the builder for creating many Checklist entities in bulk.
type ChecklistCreateBulk struct {
	config
	err      error
	builders []*ChecklistCreate
}

// Save creates the Checklist entities in the database.
func (_c *ChecklistCreateBulk) Save(ctx context.Context) ([]*Checklist, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Checklist, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChecklistMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChecklistCreateBulk) SaveX(ctx context.Context) []*Checklist {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChecklistCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChecklistCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
