// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"jkh/ent/checklist"
	"jkh/ent/checklistelement"
	"jkh/ent/predicate"
	"jkh/ent/task"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChecklistQuery is the builder for querying Checklist entities.
type ChecklistQuery struct {
	config
	ctx          *QueryContext
	order        []checklist.OrderOption
	inters       []Interceptor
	predicates   []predicate.Checklist
	withElements *ChecklistElementQuery
	withTasks    *TaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChecklistQuery builder.
func (_q *ChecklistQuery) Where(ps ...predicate.Checklist) *ChecklistQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChecklistQuery) Limit(limit int) *ChecklistQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChecklistQuery) Offset(offset int) *ChecklistQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChecklistQuery) Unique(unique bool) *ChecklistQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChecklistQuery) Order(o ...checklist.OrderOption) *ChecklistQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryElements chains the current query on the "elements" edge.
func (_q *ChecklistQuery) QueryElements() *ChecklistElementQuery {
	query := (&ChecklistElementClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(checklist.Table, checklist.FieldID, selector),
			sqlgraph.To(checklistelement.Table, checklistelement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, checklist.ElementsTable, checklist.ElementsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTasks chains the current query on the "tasks" edge.
func (_q *ChecklistQuery) QueryTasks() *TaskQuery {
	query := (&TaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(checklist.Table, checklist.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, checklist.TasksTable, checklist.TasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Checklist entity from the query.
// Returns a *NotFoundError when no Checklist was found.
func (_q *ChecklistQuery) First(ctx context.Context) (*Checklist, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{checklist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChecklistQuery) FirstX(ctx context.Context) *Checklist {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Checklist ID from the query.
// Returns a *NotFoundError when no Checklist ID was found.
func (_q *ChecklistQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{checklist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChecklistQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Checklist entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Checklist entity is found.
// Returns a *NotFoundError when no Checklist entities are found.
func (_q *ChecklistQuery) Only(ctx context.Context) (*Checklist, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{checklist.Label}
	default:
		return nil, &NotSingularError{checklist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChecklistQuery) OnlyX(ctx context.Context) *Checklist {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Checklist ID in the query.
// Returns a *NotSingularError when more than one Checklist ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChecklistQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{checklist.Label}
	default:
		err = &NotSingularError{checklist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChecklistQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Checklists.
func (_q *ChecklistQuery) All(ctx context.Context) ([]*Checklist, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Checklist, *ChecklistQuery]()
	return withInterceptors[[]*Checklist](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChecklistQuery) AllX(ctx context.Context) []*Checklist {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Checklist IDs.
func (_q *ChecklistQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(checklist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChecklistQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChecklistQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChecklistQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChecklistQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChecklistQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChecklistQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChecklistQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChecklistQuery) Clone() *ChecklistQuery {
	if _q == nil {
		return nil
	}
	return &ChecklistQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]checklist.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Checklist{}, _q.predicates...),
		withElements: _q.withElements.Clone(),
		withTasks:    _q.withTasks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithElements tells the query-builder to eager-load the nodes that are connected to
// the "elements" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChecklistQuery) WithElements(opts ...func(*ChecklistElementQuery)) *ChecklistQuery {
	query := (&ChecklistElementClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withElements = query
	return _q
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChecklistQuery) WithTasks(opts ...func(*TaskQuery)) *ChecklistQuery {
	query := (&TaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTasks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Checklist.Query().
//		GroupBy(checklist.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChecklistQuery) GroupBy(field string, fields ...string) *ChecklistGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChecklistGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = checklist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Checklist.Query().
//		Select(checklist.FieldTitle).
//		Scan(ctx, &v)
func (_q *ChecklistQuery) Select(fields ...string) *ChecklistSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChecklistSelect{ChecklistQuery: _q}
	sbuild.label = checklist.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChecklistSelect configured with the given aggregations.
func (_q *ChecklistQuery) Aggregate(fns ...AggregateFunc) *ChecklistSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChecklistQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !checklist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChecklistQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Checklist, error) {
	var (
		nodes       = []*Checklist{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withElements != nil,
			_q.withTasks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Checklist).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Checklist{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withElements; query != nil {
		if err := _q.loadElements(ctx, query, nodes,
			func(n *Checklist) { n.Edges.Elements = []*ChecklistElement{} },
			func(n *Checklist, e *ChecklistElement) { n.Edges.Elements = append(n.Edges.Elements, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTasks; query != nil {
		if err := _q.loadTasks(ctx, query, nodes,
			func(n *Checklist) { n.Edges.Tasks = []*Task{} },
			func(n *Checklist, e *Task) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChecklistQuery) loadElements(ctx context.Context, query *ChecklistElementQuery, nodes []*Checklist, init func(*Checklist), assign func(*Checklist, *ChecklistElement)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Checklist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(checklistelement.FieldChecklistID)
	}
	query.Where(predicate.ChecklistElement(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(checklist.ElementsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChecklistID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "checklist_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ChecklistQuery) loadTasks(ctx context.Context, query *TaskQuery, nodes []*Checklist, init func(*Checklist), assign func(*Checklist, *Task)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Checklist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(task.FieldChecklistID)
	}
	query.Where(predicate.Task(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(checklist.TasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChecklistID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "checklist_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ChecklistQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChecklistQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(checklist.Table, checklist.Columns, sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checklist.FieldID)
		for i := range fields {
			if fields[i] != checklist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChecklistQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(checklist.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = checklist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChecklistGroupBy is the group-by builder for Checklist entities.
type ChecklistGroupBy struct {
	selector
	build *ChecklistQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChecklistGroupBy) Aggregate(fns ...AggregateFunc) *ChecklistGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChecklistGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChecklistQuery, *ChecklistGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChecklistGroupBy) sqlScan(ctx context.Context, root *ChecklistQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChecklistSelect is the builder for selecting fields of Checklist entities.
type ChecklistSelect struct {
	*ChecklistQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChecklistSelect) Aggregate(fns ...AggregateFunc) *ChecklistSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChecklistSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChecklistQuery, *ChecklistSelect](ctx, _s.ChecklistQuery, _s, _s.inters, v)
}

func (_s *ChecklistSelect) sqlScan(ctx context.Context, root *ChecklistQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
