// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"jkh/ent/checklist"
	"jkh/ent/checklistelement"
	"jkh/ent/elementcatalog"
	"jkh/ent/inspectionresult"
	"jkh/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChecklistElementQuery is the builder for querying ChecklistElement entities.
type ChecklistElementQuery struct {
	config
	ctx                   *QueryContext
	order                 []checklistelement.OrderOption
	inters                []Interceptor
	predicates            []predicate.ChecklistElement
	withChecklist         *ChecklistQuery
	withElementCatalog    *ElementCatalogQuery
	withInspectionResults *InspectionResultQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChecklistElementQuery builder.
func (_q *ChecklistElementQuery) Where(ps ...predicate.ChecklistElement) *ChecklistElementQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChecklistElementQuery) Limit(limit int) *ChecklistElementQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChecklistElementQuery) Offset(offset int) *ChecklistElementQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChecklistElementQuery) Unique(unique bool) *ChecklistElementQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChecklistElementQuery) Order(o ...checklistelement.OrderOption) *ChecklistElementQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChecklist chains the current query on the "checklist" edge.
func (_q *ChecklistElementQuery) QueryChecklist() *ChecklistQuery {
	query := (&ChecklistClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(checklistelement.Table, checklistelement.FieldID, selector),
			sqlgraph.To(checklist.Table, checklist.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checklistelement.ChecklistTable, checklistelement.ChecklistColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryElementCatalog chains the current query on the "element_catalog" edge.
func (_q *ChecklistElementQuery) QueryElementCatalog() *ElementCatalogQuery {
	query := (&ElementCatalogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(checklistelement.Table, checklistelement.FieldID, selector),
			sqlgraph.To(elementcatalog.Table, elementcatalog.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checklistelement.ElementCatalogTable, checklistelement.ElementCatalogColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInspectionResults chains the current query on the "inspection_results" edge.
func (_q *ChecklistElementQuery) QueryInspectionResults() *InspectionResultQuery {
	query := (&InspectionResultClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(checklistelement.Table, checklistelement.FieldID, selector),
			sqlgraph.To(inspectionresult.Table, inspectionresult.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, checklistelement.InspectionResultsTable, checklistelement.InspectionResultsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChecklistElement entity from the query.
// Returns a *NotFoundError when no ChecklistElement was found.
func (_q *ChecklistElementQuery) First(ctx context.Context) (*ChecklistElement, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{checklistelement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChecklistElementQuery) FirstX(ctx context.Context) *ChecklistElement {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChecklistElement ID from the query.
// Returns a *NotFoundError when no ChecklistElement ID was found.
func (_q *ChecklistElementQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{checklistelement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChecklistElementQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChecklistElement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChecklistElement entity is found.
// Returns a *NotFoundError when no ChecklistElement entities are found.
func (_q *ChecklistElementQuery) Only(ctx context.Context) (*ChecklistElement, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{checklistelement.Label}
	default:
		return nil, &NotSingularError{checklistelement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChecklistElementQuery) OnlyX(ctx context.Context) *ChecklistElement {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChecklistElement ID in the query.
// Returns a *NotSingularError when more than one ChecklistElement ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChecklistElementQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{checklistelement.Label}
	default:
		err = &NotSingularError{checklistelement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChecklistElementQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChecklistElements.
func (_q *ChecklistElementQuery) All(ctx context.Context) ([]*ChecklistElement, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChecklistElement, *ChecklistElementQuery]()
	return withInterceptors[[]*ChecklistElement](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChecklistElementQuery) AllX(ctx context.Context) []*ChecklistElement {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChecklistElement IDs.
func (_q *ChecklistElementQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(checklistelement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChecklistElementQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChecklistElementQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChecklistElementQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChecklistElementQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChecklistElementQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChecklistElementQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChecklistElementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChecklistElementQuery) Clone() *ChecklistElementQuery {
	if _q == nil {
		return nil
	}
	return &ChecklistElementQuery{
		config:                _q.config,
		ctx:                   _q.ctx.Clone(),
		order:                 append([]checklistelement.OrderOption{}, _q.order...),
		inters:                append([]Interceptor{}, _q.inters...),
		predicates:            append([]predicate.ChecklistElement{}, _q.predicates...),
		withChecklist:         _q.withChecklist.Clone(),
		withElementCatalog:    _q.withElementCatalog.Clone(),
		withInspectionResults: _q.withInspectionResults.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChecklist tells the query-builder to eager-load the nodes that are connected to
// the "checklist" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChecklistElementQuery) WithChecklist(opts ...func(*ChecklistQuery)) *ChecklistElementQuery {
	query := (&ChecklistClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChecklist = query
	return _q
}

// WithElementCatalog tells the query-builder to eager-load the nodes that are connected to
// the "element_catalog" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChecklistElementQuery) WithElementCatalog(opts ...func(*ElementCatalogQuery)) *ChecklistElementQuery {
	query := (&ElementCatalogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withElementCatalog = query
	return _q
}

// WithInspectionResults tells the query-builder to eager-load the nodes that are connected to
// the "inspection_results" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChecklistElementQuery) WithInspectionResults(opts ...func(*InspectionResultQuery)) *ChecklistElementQuery {
	query := (&InspectionResultClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInspectionResults = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChecklistID int `json:"checklist_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChecklistElement.Query().
//		GroupBy(checklistelement.FieldChecklistID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChecklistElementQuery) GroupBy(field string, fields ...string) *ChecklistElementGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChecklistElementGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = checklistelement.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChecklistID int `json:"checklist_id,omitempty"`
//	}
//
//	client.ChecklistElement.Query().
//		Select(checklistelement.FieldChecklistID).
//		Scan(ctx, &v)
func (_q *ChecklistElementQuery) Select(fields ...string) *ChecklistElementSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChecklistElementSelect{ChecklistElementQuery: _q}
	sbuild.label = checklistelement.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChecklistElementSelect configured with the given aggregations.
func (_q *ChecklistElementQuery) Aggregate(fns ...AggregateFunc) *ChecklistElementSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChecklistElementQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !checklistelement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChecklistElementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChecklistElement, error) {
	var (
		nodes       = []*ChecklistElement{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withChecklist != nil,
			_q.withElementCatalog != nil,
			_q.withInspectionResults != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChecklistElement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChecklistElement{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChecklist; query != nil {
		if err := _q.loadChecklist(ctx, query, nodes, nil,
			func(n *ChecklistElement, e *Checklist) { n.Edges.Checklist = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withElementCatalog; query != nil {
		if err := _q.loadElementCatalog(ctx, query, nodes, nil,
			func(n *ChecklistElement, e *ElementCatalog) { n.Edges.ElementCatalog = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withInspectionResults; query != nil {
		if err := _q.loadInspectionResults(ctx, query, nodes,
			func(n *ChecklistElement) { n.Edges.InspectionResults = []*InspectionResult{} },
			func(n *ChecklistElement, e *InspectionResult) {
				n.Edges.InspectionResults = append(n.Edges.InspectionResults, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChecklistElementQuery) loadChecklist(ctx context.Context, query *ChecklistQuery, nodes []*ChecklistElement, init func(*ChecklistElement), assign func(*ChecklistElement, *Checklist)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChecklistElement)
	for i := range nodes {
		fk := nodes[i].ChecklistID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(checklist.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "checklist_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChecklistElementQuery) loadElementCatalog(ctx context.Context, query *ElementCatalogQuery, nodes []*ChecklistElement, init func(*ChecklistElement), assign func(*ChecklistElement, *ElementCatalog)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChecklistElement)
	for i := range nodes {
		fk := nodes[i].ElementID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(elementcatalog.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "element_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChecklistElementQuery) loadInspectionResults(ctx context.Context, query *InspectionResultQuery, nodes []*ChecklistElement, init func(*ChecklistElement), assign func(*ChecklistElement, *InspectionResult)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ChecklistElement)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(inspectionresult.FieldChecklistElementID)
	}
	query.Where(predicate.InspectionResult(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(checklistelement.InspectionResultsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChecklistElementID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "checklist_element_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ChecklistElementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChecklistElementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(checklistelement.Table, checklistelement.Columns, sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checklistelement.FieldID)
		for i := range fields {
			if fields[i] != checklistelement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withChecklist != nil {
			_spec.Node.AddColumnOnce(checklistelement.FieldChecklistID)
		}
		if _q.withElementCatalog != nil {
			_spec.Node.AddColumnOnce(checklistelement.FieldElementID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChecklistElementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(checklistelement.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = checklistelement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChecklistElementGroupBy is the group-by builder for ChecklistElement entities.
type ChecklistElementGroupBy struct {
	selector
	build *ChecklistElementQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChecklistElementGroupBy) Aggregate(fns ...AggregateFunc) *ChecklistElementGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChecklistElementGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChecklistElementQuery, *ChecklistElementGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChecklistElementGroupBy) sqlScan(ctx context.Context, root *ChecklistElementQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChecklistElementSelect is the builder for selecting fields of ChecklistElement entities.
type ChecklistElementSelect struct {
	*ChecklistElementQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChecklistElementSelect) Aggregate(fns ...AggregateFunc) *ChecklistElementSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChecklistElementSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChecklistElementQuery, *ChecklistElementSelect](ctx, _s.ChecklistElementQuery, _s, _s.inters, v)
}

func (_s *ChecklistElementSelect) sqlScan(ctx context.Context, root *ChecklistElementQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
