// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"jkh/ent/district"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// District is the model entity for the District schema.
type District struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Название района (уникальное).
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DistrictQuery when eager-loading is set.
	Edges        DistrictEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DistrictEdges holds the relations/edges for other nodes in the graph.
type DistrictEdges struct {
	// JkhUnits holds the value of the jkh_units edge.
	JkhUnits []*JkhUnit `json:"jkh_units,omitempty"`
	// Buildings holds the value of the buildings edge.
	Buildings []*Building `json:"buildings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// JkhUnitsOrErr returns the JkhUnits value or an error if the edge
// was not loaded in eager-loading.
func (e DistrictEdges) JkhUnitsOrErr() ([]*JkhUnit, error) {
	if e.loadedTypes[0] {
		return e.JkhUnits, nil
	}
	return nil, &NotLoadedError{edge: "jkh_units"}
}

// BuildingsOrErr returns the Buildings value or an error if the edge
// was not loaded in eager-loading.
func (e DistrictEdges) BuildingsOrErr() ([]*Building, error) {
	if e.loadedTypes[1] {
		return e.Buildings, nil
	}
	return nil, &NotLoadedError{edge: "buildings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*District) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case district.FieldID:
			values[i] = new(sql.NullInt64)
		case district.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the District fields.
func (_m *District) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case district.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case district.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the District.
// This includes values selected through modifiers, order, etc.
func (_m *District) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryJkhUnits queries the "jkh_units" edge of the District entity.
func (_m *District) QueryJkhUnits() *JkhUnitQuery {
	return NewDistrictClient(_m.config).QueryJkhUnits(_m)
}

// QueryBuildings queries the "buildings" edge of the District entity.
func (_m *District) QueryBuildings() *BuildingQuery {
	return NewDistrictClient(_m.config).QueryBuildings(_m)
}

// Update returns a builder for updating this District.
// Note that you need to call District.Unwrap() before calling this method if this District
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *District) Update() *DistrictUpdateOne {
	return NewDistrictClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the District entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *District) Unwrap() *District {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: District is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *District) String() string {
	var builder strings.Builder
	builder.WriteString("District(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Districts is a parsable slice of District.
type Districts []*District
