// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/building"
	"jkh/ent/district"
	"jkh/ent/jkhunit"
	"jkh/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DistrictUpdate is the builder for updating District entities.
type DistrictUpdate struct {
	config
	hooks    []Hook
	mutation *DistrictMutation
}

// Where appends a list predicates to the DistrictUpdate builder.
func (_u *DistrictUpdate) Where(ps ...predicate.District) *DistrictUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DistrictUpdate) SetName(v string) *DistrictUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DistrictUpdate) SetNillableName(v *string) *DistrictUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddJkhUnitIDs adds the "jkh_units" edge to the JkhUnit entity by IDs.
func (_u *DistrictUpdate) AddJkhUnitIDs(ids ...int) *DistrictUpdate {
	_u.mutation.AddJkhUnitIDs(ids...)
	return _u
}

// AddJkhUnits adds the "jkh_units" edges to the JkhUnit entity.
func (_u *DistrictUpdate) AddJkhUnits(v ...*JkhUnit) *DistrictUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJkhUnitIDs(ids...)
}

// AddBuildingIDs adds the "buildings" edge to the Building entity by IDs.
func (_u *DistrictUpdate) AddBuildingIDs(ids ...int) *DistrictUpdate {
	_u.mutation.AddBuildingIDs(ids...)
	return _u
}

// AddBuildings adds the "buildings" edges to the Building entity.
func (_u *DistrictUpdate) AddBuildings(v ...*Building) *DistrictUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBuildingIDs(ids...)
}

// Mutation returns the DistrictMutation object of the builder.
func (_u *DistrictUpdate) Mutation() *DistrictMutation {
	return _u.mutation
}

// ClearJkhUnits clears all "jkh_units" edges to the JkhUnit entity.
func (_u *DistrictUpdate) ClearJkhUnits() *DistrictUpdate {
	_u.mutation.ClearJkhUnits()
	return _u
}

// RemoveJkhUnitIDs removes the "jkh_units" edge to JkhUnit entities by IDs.
func (_u *DistrictUpdate) RemoveJkhUnitIDs(ids ...int) *DistrictUpdate {
	_u.mutation.RemoveJkhUnitIDs(ids...)
	return _u
}

// RemoveJkhUnits removes "jkh_units" edges to JkhUnit entities.
func (_u *DistrictUpdate) RemoveJkhUnits(v ...*JkhUnit) *DistrictUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJkhUnitIDs(ids...)
}

// ClearBuildings clears all "buildings" edges to the Building entity.
func (_u *DistrictUpdate) ClearBuildings() *DistrictUpdate {
	_u.mutation.ClearBuildings()
	return _u
}

// RemoveBuildingIDs removes the "buildings" edge to Building entities by IDs.
func (_u *DistrictUpdate) RemoveBuildingIDs(ids ...int) *DistrictUpdate {
	_u.mutation.RemoveBuildingIDs(ids...)
	return _u
}

// RemoveBuildings removes "buildings" edges to Building entities.
func (_u *DistrictUpdate) RemoveBuildings(v ...*Building) *DistrictUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBuildingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DistrictUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DistrictUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DistrictUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DistrictUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DistrictUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(district.Table, district.Columns, sqlgraph.NewFieldSpec(district.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(district.FieldName, field.TypeString, value)
	}
	if _u.mutation.JkhUnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.JkhUnitsTable,
			Columns: []string{district.JkhUnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jkhunit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJkhUnitsIDs(); len(nodes) > 0 && !_u.mutation.JkhUnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.JkhUnitsTable,
			Columns: []string{district.JkhUnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jkhunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JkhUnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.JkhUnitsTable,
			Columns: []string{district.JkhUnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jkhunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BuildingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.BuildingsTable,
			Columns: []string{district.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBuildingsIDs(); len(nodes) > 0 && !_u.mutation.BuildingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.BuildingsTable,
			Columns: []string{district.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BuildingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.BuildingsTable,
			Columns: []string{district.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{district.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DistrictUpdateOne is the builder for updating a single District entity.
type DistrictUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DistrictMutation
}

// SetName sets the "name" field.
func (_u *DistrictUpdateOne) SetName(v string) *DistrictUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DistrictUpdateOne) SetNillableName(v *string) *DistrictUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddJkhUnitIDs adds the "jkh_units" edge to the JkhUnit entity by IDs.
func (_u *DistrictUpdateOne) AddJkhUnitIDs(ids ...int) *DistrictUpdateOne {
	_u.mutation.AddJkhUnitIDs(ids...)
	return _u
}

// AddJkhUnits adds the "jkh_units" edges to the JkhUnit entity.
func (_u *DistrictUpdateOne) AddJkhUnits(v ...*JkhUnit) *DistrictUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJkhUnitIDs(ids...)
}

// AddBuildingIDs adds the "buildings" edge to the Building entity by IDs.
func (_u *DistrictUpdateOne) AddBuildingIDs(ids ...int) *DistrictUpdateOne {
	_u.mutation.AddBuildingIDs(ids...)
	return _u
}

// AddBuildings adds the "buildings" edges to the Building entity.
func (_u *DistrictUpdateOne) AddBuildings(v ...*Building) *DistrictUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBuildingIDs(ids...)
}

// Mutation returns the DistrictMutation object of the builder.
func (_u *DistrictUpdateOne) Mutation() *DistrictMutation {
	return _u.mutation
}

// ClearJkhUnits clears all "jkh_units" edges to the JkhUnit entity.
func (_u *DistrictUpdateOne) ClearJkhUnits() *DistrictUpdateOne {
	_u.mutation.ClearJkhUnits()
	return _u
}

// RemoveJkhUnitIDs removes the "jkh_units" edge to JkhUnit entities by IDs.
func (_u *DistrictUpdateOne) RemoveJkhUnitIDs(ids ...int) *DistrictUpdateOne {
	_u.mutation.RemoveJkhUnitIDs(ids...)
	return _u
}

// RemoveJkhUnits removes "jkh_units" edges to JkhUnit entities.
func (_u *DistrictUpdateOne) RemoveJkhUnits(v ...*JkhUnit) *DistrictUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJkhUnitIDs(ids...)
}

// ClearBuildings clears all "buildings" edges to the Building entity.
func (_u *DistrictUpdateOne) ClearBuildings() *DistrictUpdateOne {
	_u.mutation.ClearBuildings()
	return _u
}

// RemoveBuildingIDs removes the "buildings" edge to Building entities by IDs.
func (_u *DistrictUpdateOne) RemoveBuildingIDs(ids ...int) *DistrictUpdateOne {
	_u.mutation.RemoveBuildingIDs(ids...)
	return _u
}

// RemoveBuildings removes "buildings" edges to Building entities.
func (_u *DistrictUpdateOne) RemoveBuildings(v ...*Building) *DistrictUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBuildingIDs(ids...)
}

// Where appends a list predicates to the DistrictUpdate builder.
func (_u *DistrictUpdateOne) Where(ps ...predicate.District) *DistrictUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DistrictUpdateOne) Select(field string, fields ...string) *DistrictUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated District entity.
func (_u *DistrictUpdateOne) Save(ctx context.Context) (*District, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DistrictUpdateOne) SaveX(ctx context.Context) *District {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DistrictUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DistrictUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DistrictUpdateOne) sqlSave(ctx context.Context) (_node *District, err error) {
	_spec := sqlgraph.NewUpdateSpec(district.Table, district.Columns, sqlgraph.NewFieldSpec(district.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "District.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, district.FieldID)
		for _, f := range fields {
			if !district.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != district.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(district.FieldName, field.TypeString, value)
	}
	if _u.mutation.JkhUnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.JkhUnitsTable,
			Columns: []string{district.JkhUnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jkhunit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJkhUnitsIDs(); len(nodes) > 0 && !_u.mutation.JkhUnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.JkhUnitsTable,
			Columns: []string{district.JkhUnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jkhunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JkhUnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.JkhUnitsTable,
			Columns: []string{district.JkhUnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jkhunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BuildingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.BuildingsTable,
			Columns: []string{district.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBuildingsIDs(); len(nodes) > 0 && !_u.mutation.BuildingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.BuildingsTable,
			Columns: []string{district.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BuildingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   district.BuildingsTable,
			Columns: []string{district.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &District{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{district.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
