// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/checklistelement"
	"jkh/ent/elementcatalog"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ElementCatalogCreate is the builder for creating a ElementCatalog entity.
type ElementCatalogCreate struct {
	config
	mutation *ElementCatalogMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ElementCatalogCreate) SetName(v string) *ElementCatalogCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *ElementCatalogCreate) SetCategory(v string) *ElementCatalogCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *ElementCatalogCreate) SetNillableCategory(v *string) *ElementCatalogCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// AddChecklistElementIDs adds the "checklist_elements" edge to the ChecklistElement entity by IDs.
func (_c *ElementCatalogCreate) AddChecklistElementIDs(ids ...int) *ElementCatalogCreate {
	_c.mutation.AddChecklistElementIDs(ids...)
	return _c
}

// AddChecklistElements adds the "checklist_elements" edges to the ChecklistElement entity.
func (_c *ElementCatalogCreate) AddChecklistElements(v ...*ChecklistElement) *ElementCatalogCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChecklistElementIDs(ids...)
}

// Mutation returns the ElementCatalogMutation object of the builder.
func (_c *ElementCatalogCreate) Mutation() *ElementCatalogMutation {
	return _c.mutation
}

// Save creates the ElementCatalog in the database.
func (_c *ElementCatalogCreate) Save(ctx context.Context) (*ElementCatalog, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ElementCatalogCreate) SaveX(ctx context.Context) *ElementCatalog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ElementCatalogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ElementCatalogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ElementCatalogCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ElementCatalog.name"`)}
	}
	return nil
}

func (_c *ElementCatalogCreate) sqlSave(ctx context.Context) (*ElementCatalog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ElementCatalogCreate) createSpec() (*ElementCatalog, *sqlgraph.CreateSpec) {
	var (
		_node = &ElementCatalog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(elementcatalog.Table, sqlgraph.NewFieldSpec(elementcatalog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(elementcatalog.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(elementcatalog.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if nodes := _c.mutation.ChecklistElementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   elementcatalog.ChecklistElementsTable,
			Columns: []string{elementcatalog.ChecklistElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ElementCatalogCreateBulk is the builder for creating many ElementCatalog entities in bulk.
type ElementCatalogCreateBulk struct {
	config
	err      error
	builders []*ElementCatalogCreate
}

// Save creates the ElementCatalog entities in the database.
func (_c *ElementCatalogCreateBulk) Save(ctx context.Context) ([]*ElementCatalog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ElementCatalog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ElementCatalogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ElementCatalogCreateBulk) SaveX(ctx context.Context) []*ElementCatalog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ElementCatalogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ElementCatalogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
