// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"jkh/ent/elementcatalog"
	"jkh/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ElementCatalogDelete is the builder for deleting a ElementCatalog entity.
type ElementCatalogDelete struct {
	config
	hooks    []Hook
	mutation *ElementCatalogMutation
}

// Where appends a list predicates to the ElementCatalogDelete builder.
func (_d *ElementCatalogDelete) Where(ps ...predicate.ElementCatalog) *ElementCatalogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ElementCatalogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ElementCatalogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ElementCatalogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(elementcatalog.Table, sqlgraph.NewFieldSpec(elementcatalog.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ElementCatalogDeleteOne is the builder for deleting a single ElementCatalog entity.
type ElementCatalogDeleteOne struct {
	_d *ElementCatalogDelete
}

// Where appends a list predicates to the ElementCatalogDelete builder.
func (_d *ElementCatalogDeleteOne) Where(ps ...predicate.ElementCatalog) *ElementCatalogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ElementCatalogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{elementcatalog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ElementCatalogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
