// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/checklistelement"
	"jkh/ent/elementcatalog"
	"jkh/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ElementCatalogUpdate is the builder for updating ElementCatalog entities.
type ElementCatalogUpdate struct {
	config
	hooks    []Hook
	mutation *ElementCatalogMutation
}

// Where appends a list predicates to the ElementCatalogUpdate builder.
func (_u *ElementCatalogUpdate) Where(ps ...predicate.ElementCatalog) *ElementCatalogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ElementCatalogUpdate) SetName(v string) *ElementCatalogUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ElementCatalogUpdate) SetNillableName(v *string) *ElementCatalogUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ElementCatalogUpdate) SetCategory(v string) *ElementCatalogUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ElementCatalogUpdate) SetNillableCategory(v *string) *ElementCatalogUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ElementCatalogUpdate) ClearCategory() *ElementCatalogUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// AddChecklistElementIDs adds the "checklist_elements" edge to the ChecklistElement entity by IDs.
func (_u *ElementCatalogUpdate) AddChecklistElementIDs(ids ...int) *ElementCatalogUpdate {
	_u.mutation.AddChecklistElementIDs(ids...)
	return _u
}

// AddChecklistElements adds the "checklist_elements" edges to the ChecklistElement entity.
func (_u *ElementCatalogUpdate) AddChecklistElements(v ...*ChecklistElement) *ElementCatalogUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChecklistElementIDs(ids...)
}

// Mutation returns the ElementCatalogMutation object of the builder.
func (_u *ElementCatalogUpdate) Mutation() *ElementCatalogMutation {
	return _u.mutation
}

// ClearChecklistElements clears all "checklist_elements" edges to the ChecklistElement entity.
func (_u *ElementCatalogUpdate) ClearChecklistElements() *ElementCatalogUpdate {
	_u.mutation.ClearChecklistElements()
	return _u
}

// RemoveChecklistElementIDs removes the "checklist_elements" edge to ChecklistElement entities by IDs.
func (_u *ElementCatalogUpdate) RemoveChecklistElementIDs(ids ...int) *ElementCatalogUpdate {
	_u.mutation.RemoveChecklistElementIDs(ids...)
	return _u
}

// RemoveChecklistElements removes "checklist_elements" edges to ChecklistElement entities.
func (_u *ElementCatalogUpdate) RemoveChecklistElements(v ...*ChecklistElement) *ElementCatalogUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChecklistElementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ElementCatalogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ElementCatalogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ElementCatalogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ElementCatalogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ElementCatalogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(elementcatalog.Table, elementcatalog.Columns, sqlgraph.NewFieldSpec(elementcatalog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(elementcatalog.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(elementcatalog.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(elementcatalog.FieldCategory, field.TypeString)
	}
	if _u.mutation.ChecklistElementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   elementcatalog.ChecklistElementsTable,
			Columns: []string{elementcatalog.ChecklistElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChecklistElementsIDs(); len(nodes) > 0 && !_u.mutation.ChecklistElementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   elementcatalog.ChecklistElementsTable,
			Columns: []string{elementcatalog.ChecklistElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecklistElementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   elementcatalog.ChecklistElementsTable,
			Columns: []string{elementcatalog.ChecklistElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{elementcatalog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ElementCatalogUpdateOne is the builder for updating a single ElementCatalog entity.
type ElementCatalogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ElementCatalogMutation
}

// SetName sets the "name" field.
func (_u *ElementCatalogUpdateOne) SetName(v string) *ElementCatalogUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ElementCatalogUpdateOne) SetNillableName(v *string) *ElementCatalogUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ElementCatalogUpdateOne) SetCategory(v string) *ElementCatalogUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ElementCatalogUpdateOne) SetNillableCategory(v *string) *ElementCatalogUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ElementCatalogUpdateOne) ClearCategory() *ElementCatalogUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// AddChecklistElementIDs adds the "checklist_elements" edge to the ChecklistElement entity by IDs.
func (_u *ElementCatalogUpdateOne) AddChecklistElementIDs(ids ...int) *ElementCatalogUpdateOne {
	_u.mutation.AddChecklistElementIDs(ids...)
	return _u
}

// AddChecklistElements adds the "checklist_elements" edges to the ChecklistElement entity.
func (_u *ElementCatalogUpdateOne) AddChecklistElements(v ...*ChecklistElement) *ElementCatalogUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChecklistElementIDs(ids...)
}

// Mutation returns the ElementCatalogMutation object of the builder.
func (_u *ElementCatalogUpdateOne) Mutation() *ElementCatalogMutation {
	return _u.mutation
}

// ClearChecklistElements clears all "checklist_elements" edges to the ChecklistElement entity.
func (_u *ElementCatalogUpdateOne) ClearChecklistElements() *ElementCatalogUpdateOne {
	_u.mutation.ClearChecklistElements()
	return _u
}

// RemoveChecklistElementIDs removes the "checklist_elements" edge to ChecklistElement entities by IDs.
func (_u *ElementCatalogUpdateOne) RemoveChecklistElementIDs(ids ...int) *ElementCatalogUpdateOne {
	_u.mutation.RemoveChecklistElementIDs(ids...)
	return _u
}

// RemoveChecklistElements removes "checklist_elements" edges to ChecklistElement entities.
func (_u *ElementCatalogUpdateOne) RemoveChecklistElements(v ...*ChecklistElement) *ElementCatalogUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChecklistElementIDs(ids...)
}

// Where appends a list predicates to the ElementCatalogUpdate builder.
func (_u *ElementCatalogUpdateOne) Where(ps ...predicate.ElementCatalog) *ElementCatalogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ElementCatalogUpdateOne) Select(field string, fields ...string) *ElementCatalogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ElementCatalog entity.
func (_u *ElementCatalogUpdateOne) Save(ctx context.Context) (*ElementCatalog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ElementCatalogUpdateOne) SaveX(ctx context.Context) *ElementCatalog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ElementCatalogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ElementCatalogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ElementCatalogUpdateOne) sqlSave(ctx context.Context) (_node *ElementCatalog, err error) {
	_spec := sqlgraph.NewUpdateSpec(elementcatalog.Table, elementcatalog.Columns, sqlgraph.NewFieldSpec(elementcatalog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ElementCatalog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, elementcatalog.FieldID)
		for _, f := range fields {
			if !elementcatalog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != elementcatalog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(elementcatalog.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(elementcatalog.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(elementcatalog.FieldCategory, field.TypeString)
	}
	if _u.mutation.ChecklistElementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   elementcatalog.ChecklistElementsTable,
			Columns: []string{elementcatalog.ChecklistElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChecklistElementsIDs(); len(nodes) > 0 && !_u.mutation.ChecklistElementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   elementcatalog.ChecklistElementsTable,
			Columns: []string{elementcatalog.ChecklistElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecklistElementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   elementcatalog.ChecklistElementsTable,
			Columns: []string{elementcatalog.ChecklistElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ElementCatalog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{elementcatalog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
