// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/checklistelement"
	"jkh/ent/inspectionresult"
	"jkh/ent/task"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InspectionResultCreate is the builder for creating a InspectionResult entity.
type InspectionResultCreate struct {
	config
	mutation *InspectionResultMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *InspectionResultCreate) SetTaskID(v int) *InspectionResultCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetChecklistElementID sets the "checklist_element_id" field.
func (_c *InspectionResultCreate) SetChecklistElementID(v int) *InspectionResultCreate {
	_c.mutation.SetChecklistElementID(v)
	return _c
}

// SetConditionStatus sets the "condition_status" field.
func (_c *InspectionResultCreate) SetConditionStatus(v inspectionresult.ConditionStatus) *InspectionResultCreate {
	_c.mutation.SetConditionStatus(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *InspectionResultCreate) SetComment(v string) *InspectionResultCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *InspectionResultCreate) SetNillableComment(v *string) *InspectionResultCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InspectionResultCreate) SetCreatedAt(v time.Time) *InspectionResultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InspectionResultCreate) SetNillableCreatedAt(v *time.Time) *InspectionResultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InspectionResultCreate) SetUpdatedAt(v time.Time) *InspectionResultCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InspectionResultCreate) SetNillableUpdatedAt(v *time.Time) *InspectionResultCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *InspectionResultCreate) SetTask(v *Task) *InspectionResultCreate {
	return _c.SetTaskID(v.ID)
}

// SetChecklistElement sets the "checklist_element" edge to the ChecklistElement entity.
func (_c *InspectionResultCreate) SetChecklistElement(v *ChecklistElement) *InspectionResultCreate {
	return _c.SetChecklistElementID(v.ID)
}

// Mutation returns the InspectionResultMutation object of the builder.
func (_c *InspectionResultCreate) Mutation() *InspectionResultMutation {
	return _c.mutation
}

// Save creates the InspectionResult in the database.
func (_c *InspectionResultCreate) Save(ctx context.Context) (*InspectionResult, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InspectionResultCreate) SaveX(ctx context.Context) *InspectionResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InspectionResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InspectionResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InspectionResultCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := inspectionresult.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := inspectionresult.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InspectionResultCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "InspectionResult.task_id"`)}
	}
	if _, ok := _c.mutation.ChecklistElementID(); !ok {
		return &ValidationError{Name: "checklist_element_id", err: errors.New(`ent: missing required field "InspectionResult.checklist_element_id"`)}
	}
	if _, ok := _c.mutation.ConditionStatus(); !ok {
		return &ValidationError{Name: "condition_status", err: errors.New(`ent: missing required field "InspectionResult.condition_status"`)}
	}
	if v, ok := _c.mutation.ConditionStatus(); ok {
		if err := inspectionresult.ConditionStatusValidator(v); err != nil {
			return &ValidationError{Name: "condition_status", err: fmt.Errorf(`ent: validator failed for field "InspectionResult.condition_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InspectionResult.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InspectionResult.updated_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "InspectionResult.task"`)}
	}
	if len(_c.mutation.ChecklistElementIDs()) == 0 {
		return &ValidationError{Name: "checklist_element", err: errors.New(`ent: missing required edge "InspectionResult.checklist_element"`)}
	}
	return nil
}

func (_c *InspectionResultCreate) sqlSave(ctx context.Context) (*InspectionResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InspectionResultCreate) createSpec() (*InspectionResult, *sqlgraph.CreateSpec) {
	var (
		_node = &InspectionResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inspectionresult.Table, sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ConditionStatus(); ok {
		_spec.SetField(inspectionresult.FieldConditionStatus, field.TypeEnum, value)
		_node.ConditionStatus = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(inspectionresult.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(inspectionresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(inspectionresult.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inspectionresult.TaskTable,
			Columns: []string{inspectionresult.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChecklistElementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inspectionresult.ChecklistElementTable,
			Columns: []string{inspectionresult.ChecklistElementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklistelement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChecklistElementID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InspectionResultCreateBulk is the builder for creating many InspectionResult entities in bulk.
type InspectionResultCreateBulk struct {
	config
	err      error
	builders []*InspectionResultCreate
}

// Save creates the InspectionResult entities in the database.
func (_c *InspectionResultCreateBulk) Save(ctx context.Context) ([]*InspectionResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InspectionResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InspectionResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InspectionResultCreateBulk) SaveX(ctx context.Context) []*InspectionResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InspectionResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InspectionResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
