// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/inspectorunit"
	"jkh/ent/jkhunit"
	"jkh/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InspectorUnitCreate is the builder for creating a InspectorUnit entity.
type InspectorUnitCreate struct {
	config
	mutation *InspectorUnitMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *InspectorUnitCreate) SetUserID(v int) *InspectorUnitCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetJkhUnitID sets the "jkh_unit_id" field.
func (_c *InspectorUnitCreate) SetJkhUnitID(v int) *InspectorUnitCreate {
	_c.mutation.SetJkhUnitID(v)
	return _c
}

// SetInspectorID sets the "inspector" edge to the User entity by ID.
func (_c *InspectorUnitCreate) SetInspectorID(id int) *InspectorUnitCreate {
	_c.mutation.SetInspectorID(id)
	return _c
}

// SetInspector sets the "inspector" edge to the User entity.
func (_c *InspectorUnitCreate) SetInspector(v *User) *InspectorUnitCreate {
	return _c.SetInspectorID(v.ID)
}

// SetJkhUnit sets the "jkh_unit" edge to the JkhUnit entity.
func (_c *InspectorUnitCreate) SetJkhUnit(v *JkhUnit) *InspectorUnitCreate {
	return _c.SetJkhUnitID(v.ID)
}

// Mutation returns the InspectorUnitMutation object of the builder.
func (_c *InspectorUnitCreate) Mutation() *InspectorUnitMutation {
	return _c.mutation
}

// Save creates the InspectorUnit in the database.
func (_c *InspectorUnitCreate) Save(ctx context.Context) (*InspectorUnit, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InspectorUnitCreate) SaveX(ctx context.Context) *InspectorUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InspectorUnitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InspectorUnitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InspectorUnitCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InspectorUnit.user_id"`)}
	}
	if _, ok := _c.mutation.JkhUnitID(); !ok {
		return &ValidationError{Name: "jkh_unit_id", err: errors.New(`ent: missing required field "InspectorUnit.jkh_unit_id"`)}
	}
	if len(_c.mutation.InspectorIDs()) == 0 {
		return &ValidationError{Name: "inspector", err: errors.New(`ent: missing required edge "InspectorUnit.inspector"`)}
	}
	if len(_c.mutation.JkhUnitIDs()) == 0 {
		return &ValidationError{Name: "jkh_unit", err: errors.New(`ent: missing required edge "InspectorUnit.jkh_unit"`)}
	}
	return nil
}

func (_c *InspectorUnitCreate) sqlSave(ctx context.Context) (*InspectorUnit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InspectorUnitCreate) createSpec() (*InspectorUnit, *sqlgraph.CreateSpec) {
	var (
		_node = &InspectorUnit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inspectorunit.Table, sqlgraph.NewFieldSpec(inspectorunit.FieldID, field.TypeInt))
	)
	if nodes := _c.mutation.InspectorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inspectorunit.InspectorTable,
			Columns: []string{inspectorunit.InspectorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.JkhUnitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inspectorunit.JkhUnitTable,
			Columns: []string{inspectorunit.JkhUnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jkhunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.JkhUnitID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InspectorUnitCreateBulk is the builder for creating many InspectorUnit entities in bulk.
type InspectorUnitCreateBulk struct {
	config
	err      error
	builders []*InspectorUnitCreate
}

// Save creates the InspectorUnit entities in the database.
func (_c *InspectorUnitCreateBulk) Save(ctx context.Context) ([]*InspectorUnit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InspectorUnit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InspectorUnitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InspectorUnitCreateBulk) SaveX(ctx context.Context) []*InspectorUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InspectorUnitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InspectorUnitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
