// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"jkh/ent/checklistelement"
	"jkh/ent/inspectionresult"
	"jkh/ent/task"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// InspectionResult is the model entity for the InspectionResult schema.
type InspectionResult struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID int `json:"task_id,omitempty"`
	// ChecklistElementID holds the value of the "checklist_element_id" field.
	ChecklistElementID int `json:"checklist_element_id,omitempty"`
	// Статус состояния: Исправное, Удовлетворительное, Неудовлетворительное, Аварийное.
	ConditionStatus inspectionresult.ConditionStatus `json:"condition_status,omitempty"`
	// Comment holds the value of the "comment" field.
	Comment string `json:"comment,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InspectionResultQuery when eager-loading is set.
	Edges        InspectionResultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InspectionResultEdges holds the relations/edges for other nodes in the graph.
type InspectionResultEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// ChecklistElement holds the value of the checklist_element edge.
	ChecklistElement *ChecklistElement `json:"checklist_element,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InspectionResultEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// ChecklistElementOrErr returns the ChecklistElement value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InspectionResultEdges) ChecklistElementOrErr() (*ChecklistElement, error) {
	if e.ChecklistElement != nil {
		return e.ChecklistElement, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: checklistelement.Label}
	}
	return nil, &NotLoadedError{edge: "checklist_element"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InspectionResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inspectionresult.FieldID, inspectionresult.FieldTaskID, inspectionresult.FieldChecklistElementID:
			values[i] = new(sql.NullInt64)
		case inspectionresult.FieldConditionStatus, inspectionresult.FieldComment:
			values[i] = new(sql.NullString)
		case inspectionresult.FieldCreatedAt, inspectionresult.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InspectionResult fields.
func (_m *InspectionResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inspectionresult.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case inspectionresult.FieldTaskID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = int(value.Int64)
			}
		case inspectionresult.FieldChecklistElementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field checklist_element_id", values[i])
			} else if value.Valid {
				_m.ChecklistElementID = int(value.Int64)
			}
		case inspectionresult.FieldConditionStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field condition_status", values[i])
			} else if value.Valid {
				_m.ConditionStatus = inspectionresult.ConditionStatus(value.String)
			}
		case inspectionresult.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = value.String
			}
		case inspectionresult.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case inspectionresult.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InspectionResult.
// This includes values selected through modifiers, order, etc.
func (_m *InspectionResult) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the InspectionResult entity.
func (_m *InspectionResult) QueryTask() *TaskQuery {
	return NewInspectionResultClient(_m.config).QueryTask(_m)
}

// QueryChecklistElement queries the "checklist_element" edge of the InspectionResult entity.
func (_m *InspectionResult) QueryChecklistElement() *ChecklistElementQuery {
	return NewInspectionResultClient(_m.config).QueryChecklistElement(_m)
}

// Update returns a builder for updating this InspectionResult.
// Note that you need to call InspectionResult.Unwrap() before calling this method if this InspectionResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InspectionResult) Update() *InspectionResultUpdateOne {
	return NewInspectionResultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InspectionResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InspectionResult) Unwrap() *InspectionResult {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InspectionResult is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InspectionResult) String() string {
	var builder strings.Builder
	builder.WriteString("InspectionResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("checklist_element_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChecklistElementID))
	builder.WriteString(", ")
	builder.WriteString("condition_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConditionStatus))
	builder.WriteString(", ")
	builder.WriteString("comment=")
	builder.WriteString(_m.Comment)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InspectionResults is a parsable slice of InspectionResult.
type InspectionResults []*InspectionResult
