// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"jkh/ent/district"
	"jkh/ent/jkhunit"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// JkhUnit is the model entity for the JkhUnit schema.
type JkhUnit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DistrictID holds the value of the "district_id" field.
	DistrictID int `json:"district_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the JkhUnitQuery when eager-loading is set.
	Edges        JkhUnitEdges `json:"edges"`
	selectValues sql.SelectValues
}

// JkhUnitEdges holds the relations/edges for other nodes in the graph.
type JkhUnitEdges struct {
	// District holds the value of the district edge.
	District *District `json:"district,omitempty"`
	// Buildings holds the value of the buildings edge.
	Buildings []*Building `json:"buildings,omitempty"`
	// AssignedInspectors holds the value of the assigned_inspectors edge.
	AssignedInspectors []*InspectorUnit `json:"assigned_inspectors,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DistrictOrErr returns the District value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JkhUnitEdges) DistrictOrErr() (*District, error) {
	if e.District != nil {
		return e.District, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: district.Label}
	}
	return nil, &NotLoadedError{edge: "district"}
}

// BuildingsOrErr returns the Buildings value or an error if the edge
// was not loaded in eager-loading.
func (e JkhUnitEdges) BuildingsOrErr() ([]*Building, error) {
	if e.loadedTypes[1] {
		return e.Buildings, nil
	}
	return nil, &NotLoadedError{edge: "buildings"}
}

// AssignedInspectorsOrErr returns the AssignedInspectors value or an error if the edge
// was not loaded in eager-loading.
func (e JkhUnitEdges) AssignedInspectorsOrErr() ([]*InspectorUnit, error) {
	if e.loadedTypes[2] {
		return e.AssignedInspectors, nil
	}
	return nil, &NotLoadedError{edge: "assigned_inspectors"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JkhUnit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jkhunit.FieldID, jkhunit.FieldDistrictID:
			values[i] = new(sql.NullInt64)
		case jkhunit.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JkhUnit fields.
func (_m *JkhUnit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jkhunit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case jkhunit.FieldDistrictID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field district_id", values[i])
			} else if value.Valid {
				_m.DistrictID = int(value.Int64)
			}
		case jkhunit.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JkhUnit.
// This includes values selected through modifiers, order, etc.
func (_m *JkhUnit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDistrict queries the "district" edge of the JkhUnit entity.
func (_m *JkhUnit) QueryDistrict() *DistrictQuery {
	return NewJkhUnitClient(_m.config).QueryDistrict(_m)
}

// QueryBuildings queries the "buildings" edge of the JkhUnit entity.
func (_m *JkhUnit) QueryBuildings() *BuildingQuery {
	return NewJkhUnitClient(_m.config).QueryBuildings(_m)
}

// QueryAssignedInspectors queries the "assigned_inspectors" edge of the JkhUnit entity.
func (_m *JkhUnit) QueryAssignedInspectors() *InspectorUnitQuery {
	return NewJkhUnitClient(_m.config).QueryAssignedInspectors(_m)
}

// Update returns a builder for updating this JkhUnit.
// Note that you need to call JkhUnit.Unwrap() before calling this method if this JkhUnit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *JkhUnit) Update() *JkhUnitUpdateOne {
	return NewJkhUnitClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the JkhUnit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *JkhUnit) Unwrap() *JkhUnit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: JkhUnit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *JkhUnit) String() string {
	var builder strings.Builder
	builder.WriteString("JkhUnit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("district_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DistrictID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// JkhUnits is a parsable slice of JkhUnit.
type JkhUnits []*JkhUnit
