// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"jkh/ent/jkhunit"
	"jkh/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JkhUnitDelete is the builder for deleting a JkhUnit entity.
type JkhUnitDelete struct {
	config
	hooks    []Hook
	mutation *JkhUnitMutation
}

// Where appends a list predicates to the JkhUnitDelete builder.
func (_d *JkhUnitDelete) Where(ps ...predicate.JkhUnit) *JkhUnitDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *JkhUnitDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *JkhUnitDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *JkhUnitDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(jkhunit.Table, sqlgraph.NewFieldSpec(jkhunit.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// JkhUnitDeleteOne is the builder for deleting a single JkhUnit entity.
type JkhUnitDeleteOne struct {
	_d *JkhUnitDelete
}

// Where appends a list predicates to the JkhUnitDelete builder.
func (_d *JkhUnitDeleteOne) Where(ps ...predicate.JkhUnit) *JkhUnitDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *JkhUnitDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jkhunit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *JkhUnitDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
