// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/building"
	"jkh/ent/district"
	"jkh/ent/inspectorunit"
	"jkh/ent/jkhunit"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JkhUnitCreate is the builder for creating a JkhUnit entity.
type JkhUnitCreate struct {
	config
	mutation *JkhUnitMutation
	hooks    []Hook
}

// SetDistrictID sets the "district_id" field.
func (_c *JkhUnitCreate) SetDistrictID(v int) *JkhUnitCreate {
	_c.mutation.SetDistrictID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *JkhUnitCreate) SetName(v string) *JkhUnitCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDistrict sets the "district" edge to the District entity.
func (_c *JkhUnitCreate) SetDistrict(v *District) *JkhUnitCreate {
	return _c.SetDistrictID(v.ID)
}

// AddBuildingIDs adds the "buildings" edge to the Building entity by IDs.
func (_c *JkhUnitCreate) AddBuildingIDs(ids ...int) *JkhUnitCreate {
	_c.mutation.AddBuildingIDs(ids...)
	return _c
}

// AddBuildings adds the "buildings" edges to the Building entity.
func (_c *JkhUnitCreate) AddBuildings(v ...*Building) *JkhUnitCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBuildingIDs(ids...)
}

// AddAssignedInspectorIDs adds the "assigned_inspectors" edge to the InspectorUnit entity by IDs.
func (_c *JkhUnitCreate) AddAssignedInspectorIDs(ids ...int) *JkhUnitCreate {
	_c.mutation.AddAssignedInspectorIDs(ids...)
	return _c
}

// AddAssignedInspectors adds the "assigned_inspectors" edges to the InspectorUnit entity.
func (_c *JkhUnitCreate) AddAssignedInspectors(v ...*InspectorUnit) *JkhUnitCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssignedInspectorIDs(ids...)
}

// Mutation returns the JkhUnitMutation object of the builder.
func (_c *JkhUnitCreate) Mutation() *JkhUnitMutation {
	return _c.mutation
}

// Save creates the JkhUnit in the database.
func (_c *JkhUnitCreate) Save(ctx context.Context) (*JkhUnit, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JkhUnitCreate) SaveX(ctx context.Context) *JkhUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JkhUnitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JkhUnitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JkhUnitCreate) check() error {
	if _, ok := _c.mutation.DistrictID(); !ok {
		return &ValidationError{Name: "district_id", err: errors.New(`ent: missing required field "JkhUnit.district_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "JkhUnit.name"`)}
	}
	if len(_c.mutation.DistrictIDs()) == 0 {
		return &ValidationError{Name: "district", err: errors.New(`ent: missing required edge "JkhUnit.district"`)}
	}
	return nil
}

func (_c *JkhUnitCreate) sqlSave(ctx context.Context) (*JkhUnit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JkhUnitCreate) createSpec() (*JkhUnit, *sqlgraph.CreateSpec) {
	var (
		_node = &JkhUnit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(jkhunit.Table, sqlgraph.NewFieldSpec(jkhunit.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(jkhunit.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   jkhunit.DistrictTable,
			Columns: []string{jkhunit.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DistrictID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BuildingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   jkhunit.BuildingsTable,
			Columns: []string{jkhunit.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignedInspectorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   jkhunit.AssignedInspectorsTable,
			Columns: []string{jkhunit.AssignedInspectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectorunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JkhUnitCreateBulk is the builder for creating many JkhUnit entities in bulk.
type JkhUnitCreateBulk struct {
	config
	err      error
	builders []*JkhUnitCreate
}

// Save creates the JkhUnit entities in the database.
func (_c *JkhUnitCreateBulk) Save(ctx context.Context) ([]*JkhUnit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*JkhUnit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JkhUnitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JkhUnitCreateBulk) SaveX(ctx context.Context) []*JkhUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JkhUnitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JkhUnitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
