// Code generated by ent, DO NOT EDIT.

package ent

import (
	"jkh/ent/building"
	"jkh/ent/checklist"
	"jkh/ent/inspectionact"
	"jkh/ent/inspectionresult"
	"jkh/ent/schema"
	"jkh/ent/task"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	buildingFields := schema.Building{}.Fields()
	_ = buildingFields
	// buildingDescPhoto is the schema descriptor for photo field.
	buildingDescPhoto := buildingFields[6].Descriptor()
	// building.PhotoValidator is a validator for the "photo" field. It is called by the builders before save.
	building.PhotoValidator = buildingDescPhoto.Validators[0].(func(string) error)
	checklistFields := schema.Checklist{}.Fields()
	_ = checklistFields
	// checklistDescCreatedAt is the schema descriptor for created_at field.
	checklistDescCreatedAt := checklistFields[3].Descriptor()
	// checklist.DefaultCreatedAt holds the default value on creation for the created_at field.
	checklist.DefaultCreatedAt = checklistDescCreatedAt.Default.(func() time.Time)
	inspectionactFields := schema.InspectionAct{}.Fields()
	_ = inspectionactFields
	// inspectionactDescCreatedAt is the schema descriptor for created_at field.
	inspectionactDescCreatedAt := inspectionactFields[1].Descriptor()
	// inspectionact.DefaultCreatedAt holds the default value on creation for the created_at field.
	inspectionact.DefaultCreatedAt = inspectionactDescCreatedAt.Default.(func() time.Time)
	// inspectionactDescStatus is the schema descriptor for status field.
	inspectionactDescStatus := inspectionactFields[3].Descriptor()
	// inspectionact.DefaultStatus holds the default value on creation for the status field.
	inspectionact.DefaultStatus = inspectionactDescStatus.Default.(string)
	// inspectionactDescDocumentPath is the schema descriptor for document_path field.
	inspectionactDescDocumentPath := inspectionactFields[5].Descriptor()
	// inspectionact.DocumentPathValidator is a validator for the "document_path" field. It is called by the builders before save.
	inspectionact.DocumentPathValidator = inspectionactDescDocumentPath.Validators[0].(func(string) error)
	inspectionresultFields := schema.InspectionResult{}.Fields()
	_ = inspectionresultFields
	// inspectionresultDescCreatedAt is the schema descriptor for created_at field.
	inspectionresultDescCreatedAt := inspectionresultFields[4].Descriptor()
	// inspectionresult.DefaultCreatedAt holds the default value on creation for the created_at field.
	inspectionresult.DefaultCreatedAt = inspectionresultDescCreatedAt.Default.(func() time.Time)
	// inspectionresultDescUpdatedAt is the schema descriptor for updated_at field.
	inspectionresultDescUpdatedAt := inspectionresultFields[5].Descriptor()
	// inspectionresult.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	inspectionresult.DefaultUpdatedAt = inspectionresultDescUpdatedAt.Default.(func() time.Time)
	// inspectionresult.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	inspectionresult.UpdateDefaultUpdatedAt = inspectionresultDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[4].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(string)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[8].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[9].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
}
