// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jkh/ent/building"
	"jkh/ent/checklist"
	"jkh/ent/inspectionact"
	"jkh/ent/inspectionresult"
	"jkh/ent/predicate"
	"jkh/ent/task"
	"jkh/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBuildingID sets the "building_id" field.
func (_u *TaskUpdate) SetBuildingID(v int) *TaskUpdate {
	_u.mutation.SetBuildingID(v)
	return _u
}

// SetNillableBuildingID sets the "building_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableBuildingID(v *int) *TaskUpdate {
	if v != nil {
		_u.SetBuildingID(*v)
	}
	return _u
}

// SetChecklistID sets the "checklist_id" field.
func (_u *TaskUpdate) SetChecklistID(v int) *TaskUpdate {
	_u.mutation.SetChecklistID(v)
	return _u
}

// SetNillableChecklistID sets the "checklist_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableChecklistID(v *int) *TaskUpdate {
	if v != nil {
		_u.SetChecklistID(*v)
	}
	return _u
}

// SetInspectorID sets the "inspector_id" field.
func (_u *TaskUpdate) SetInspectorID(v int) *TaskUpdate {
	_u.mutation.SetInspectorID(v)
	return _u
}

// SetNillableInspectorID sets the "inspector_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableInspectorID(v *int) *TaskUpdate {
	if v != nil {
		_u.SetInspectorID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdate) SetTitle(v string) *TaskUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTitle(v *string) *TaskUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdate) SetPriority(v string) *TaskUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePriority(v *string) *TaskUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v task.Status) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *task.Status) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdate) SetDescription(v string) *TaskUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDescription(v *string) *TaskUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdate) ClearDescription() *TaskUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetScheduledDate sets the "scheduled_date" field.
func (_u *TaskUpdate) SetScheduledDate(v time.Time) *TaskUpdate {
	_u.mutation.SetScheduledDate(v)
	return _u
}

// SetNillableScheduledDate sets the "scheduled_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableScheduledDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetScheduledDate(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetInspector sets the "inspector" edge to the User entity.
func (_u *TaskUpdate) SetInspector(v *User) *TaskUpdate {
	return _u.SetInspectorID(v.ID)
}

// SetBuilding sets the "building" edge to the Building entity.
func (_u *TaskUpdate) SetBuilding(v *Building) *TaskUpdate {
	return _u.SetBuildingID(v.ID)
}

// SetChecklist sets the "checklist" edge to the Checklist entity.
func (_u *TaskUpdate) SetChecklist(v *Checklist) *TaskUpdate {
	return _u.SetChecklistID(v.ID)
}

// AddResultIDs adds the "results" edge to the InspectionResult entity by IDs.
func (_u *TaskUpdate) AddResultIDs(ids ...int) *TaskUpdate {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the InspectionResult entity.
func (_u *TaskUpdate) AddResults(v ...*InspectionResult) *TaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// SetActID sets the "act" edge to the InspectionAct entity by ID.
func (_u *TaskUpdate) SetActID(id int) *TaskUpdate {
	_u.mutation.SetActID(id)
	return _u
}

// SetNillableActID sets the "act" edge to the InspectionAct entity by ID if the given value is not nil.
func (_u *TaskUpdate) SetNillableActID(id *int) *TaskUpdate {
	if id != nil {
		_u = _u.SetActID(*id)
	}
	return _u
}

// SetAct sets the "act" edge to the InspectionAct entity.
func (_u *TaskUpdate) SetAct(v *InspectionAct) *TaskUpdate {
	return _u.SetActID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearInspector clears the "inspector" edge to the User entity.
func (_u *TaskUpdate) ClearInspector() *TaskUpdate {
	_u.mutation.ClearInspector()
	return _u
}

// ClearBuilding clears the "building" edge to the Building entity.
func (_u *TaskUpdate) ClearBuilding() *TaskUpdate {
	_u.mutation.ClearBuilding()
	return _u
}

// ClearChecklist clears the "checklist" edge to the Checklist entity.
func (_u *TaskUpdate) ClearChecklist() *TaskUpdate {
	_u.mutation.ClearChecklist()
	return _u
}

// ClearResults clears all "results" edges to the InspectionResult entity.
func (_u *TaskUpdate) ClearResults() *TaskUpdate {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to InspectionResult entities by IDs.
func (_u *TaskUpdate) RemoveResultIDs(ids ...int) *TaskUpdate {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to InspectionResult entities.
func (_u *TaskUpdate) RemoveResults(v ...*InspectionResult) *TaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// ClearAct clears the "act" edge to the InspectionAct entity.
func (_u *TaskUpdate) ClearAct() *TaskUpdate {
	_u.mutation.ClearAct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if _u.mutation.InspectorCleared() && len(_u.mutation.InspectorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.inspector"`)
	}
	if _u.mutation.BuildingCleared() && len(_u.mutation.BuildingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.building"`)
	}
	if _u.mutation.ChecklistCleared() && len(_u.mutation.ChecklistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.checklist"`)
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ScheduledDate(); ok {
		_spec.SetField(task.FieldScheduledDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InspectorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.InspectorTable,
			Columns: []string{task.InspectorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InspectorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.InspectorTable,
			Columns: []string{task.InspectorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BuildingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.BuildingTable,
			Columns: []string{task.BuildingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BuildingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.BuildingTable,
			Columns: []string{task.BuildingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChecklistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ChecklistTable,
			Columns: []string{task.ChecklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ChecklistTable,
			Columns: []string{task.ChecklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ResultsTable,
			Columns: []string{task.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ResultsTable,
			Columns: []string{task.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ResultsTable,
			Columns: []string{task.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.ActTable,
			Columns: []string{task.ActColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.ActTable,
			Columns: []string{task.ActColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetBuildingID sets the "building_id" field.
func (_u *TaskUpdateOne) SetBuildingID(v int) *TaskUpdateOne {
	_u.mutation.SetBuildingID(v)
	return _u
}

// SetNillableBuildingID sets the "building_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableBuildingID(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetBuildingID(*v)
	}
	return _u
}

// SetChecklistID sets the "checklist_id" field.
func (_u *TaskUpdateOne) SetChecklistID(v int) *TaskUpdateOne {
	_u.mutation.SetChecklistID(v)
	return _u
}

// SetNillableChecklistID sets the "checklist_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableChecklistID(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetChecklistID(*v)
	}
	return _u
}

// SetInspectorID sets the "inspector_id" field.
func (_u *TaskUpdateOne) SetInspectorID(v int) *TaskUpdateOne {
	_u.mutation.SetInspectorID(v)
	return _u
}

// SetNillableInspectorID sets the "inspector_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableInspectorID(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetInspectorID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdateOne) SetTitle(v string) *TaskUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTitle(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdateOne) SetPriority(v string) *TaskUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePriority(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v task.Status) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *task.Status) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdateOne) SetDescription(v string) *TaskUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDescription(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdateOne) ClearDescription() *TaskUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetScheduledDate sets the "scheduled_date" field.
func (_u *TaskUpdateOne) SetScheduledDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetScheduledDate(v)
	return _u
}

// SetNillableScheduledDate sets the "scheduled_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableScheduledDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetScheduledDate(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetInspector sets the "inspector" edge to the User entity.
func (_u *TaskUpdateOne) SetInspector(v *User) *TaskUpdateOne {
	return _u.SetInspectorID(v.ID)
}

// SetBuilding sets the "building" edge to the Building entity.
func (_u *TaskUpdateOne) SetBuilding(v *Building) *TaskUpdateOne {
	return _u.SetBuildingID(v.ID)
}

// SetChecklist sets the "checklist" edge to the Checklist entity.
func (_u *TaskUpdateOne) SetChecklist(v *Checklist) *TaskUpdateOne {
	return _u.SetChecklistID(v.ID)
}

// AddResultIDs adds the "results" edge to the InspectionResult entity by IDs.
func (_u *TaskUpdateOne) AddResultIDs(ids ...int) *TaskUpdateOne {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the InspectionResult entity.
func (_u *TaskUpdateOne) AddResults(v ...*InspectionResult) *TaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// SetActID sets the "act" edge to the InspectionAct entity by ID.
func (_u *TaskUpdateOne) SetActID(id int) *TaskUpdateOne {
	_u.mutation.SetActID(id)
	return _u
}

// SetNillableActID sets the "act" edge to the InspectionAct entity by ID if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableActID(id *int) *TaskUpdateOne {
	if id != nil {
		_u = _u.SetActID(*id)
	}
	return _u
}

// SetAct sets the "act" edge to the InspectionAct entity.
func (_u *TaskUpdateOne) SetAct(v *InspectionAct) *TaskUpdateOne {
	return _u.SetActID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearInspector clears the "inspector" edge to the User entity.
func (_u *TaskUpdateOne) ClearInspector() *TaskUpdateOne {
	_u.mutation.ClearInspector()
	return _u
}

// ClearBuilding clears the "building" edge to the Building entity.
func (_u *TaskUpdateOne) ClearBuilding() *TaskUpdateOne {
	_u.mutation.ClearBuilding()
	return _u
}

// ClearChecklist clears the "checklist" edge to the Checklist entity.
func (_u *TaskUpdateOne) ClearChecklist() *TaskUpdateOne {
	_u.mutation.ClearChecklist()
	return _u
}

// ClearResults clears all "results" edges to the InspectionResult entity.
func (_u *TaskUpdateOne) ClearResults() *TaskUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to InspectionResult entities by IDs.
func (_u *TaskUpdateOne) RemoveResultIDs(ids ...int) *TaskUpdateOne {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to InspectionResult entities.
func (_u *TaskUpdateOne) RemoveResults(v ...*InspectionResult) *TaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// ClearAct clears the "act" edge to the InspectionAct entity.
func (_u *TaskUpdateOne) ClearAct() *TaskUpdateOne {
	_u.mutation.ClearAct()
	return _u
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if _u.mutation.InspectorCleared() && len(_u.mutation.InspectorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.inspector"`)
	}
	if _u.mutation.BuildingCleared() && len(_u.mutation.BuildingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.building"`)
	}
	if _u.mutation.ChecklistCleared() && len(_u.mutation.ChecklistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.checklist"`)
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ScheduledDate(); ok {
		_spec.SetField(task.FieldScheduledDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InspectorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.InspectorTable,
			Columns: []string{task.InspectorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InspectorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.InspectorTable,
			Columns: []string{task.InspectorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BuildingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.BuildingTable,
			Columns: []string{task.BuildingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BuildingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.BuildingTable,
			Columns: []string{task.BuildingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChecklistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ChecklistTable,
			Columns: []string{task.ChecklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ChecklistTable,
			Columns: []string{task.ChecklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checklist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ResultsTable,
			Columns: []string{task.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ResultsTable,
			Columns: []string{task.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ResultsTable,
			Columns: []string{task.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.ActTable,
			Columns: []string{task.ActColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.ActTable,
			Columns: []string{task.ActColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inspectionact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
