// Code generated by ent, DO NOT EDIT.

package building

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the building type in the database.
	Label = "building"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDistrictID holds the string denoting the district_id field in the database.
	FieldDistrictID = "district_id"
	// FieldJkhUnitID holds the string denoting the jkh_unit_id field in the database.
	FieldJkhUnitID = "jkh_unit_id"
	// FieldInspectorID holds the string denoting the inspector_id field in the database.
	FieldInspectorID = "inspector_id"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldConstructionYear holds the string denoting the construction_year field in the database.
	FieldConstructionYear = "construction_year"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPhoto holds the string denoting the photo field in the database.
	FieldPhoto = "photo"
	// EdgeJkhUnit holds the string denoting the jkh_unit edge name in mutations.
	EdgeJkhUnit = "jkh_unit"
	// EdgeDistrict holds the string denoting the district edge name in mutations.
	EdgeDistrict = "district"
	// EdgeInspector holds the string denoting the inspector edge name in mutations.
	EdgeInspector = "inspector"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// Table holds the table name of the building in the database.
	Table = "buildings"
	// JkhUnitTable is the table that holds the jkh_unit relation/edge.
	JkhUnitTable = "buildings"
	// JkhUnitInverseTable is the table name for the JkhUnit entity.
	// It exists in this package in order to avoid circular dependency with the "jkhunit" package.
	JkhUnitInverseTable = "jkh_units"
	// JkhUnitColumn is the table column denoting the jkh_unit relation/edge.
	JkhUnitColumn = "jkh_unit_id"
	// DistrictTable is the table that holds the district relation/edge.
	DistrictTable = "buildings"
	// DistrictInverseTable is the table name for the District entity.
	// It exists in this package in order to avoid circular dependency with the "district" package.
	DistrictInverseTable = "districts"
	// DistrictColumn is the table column denoting the district relation/edge.
	DistrictColumn = "district_id"
	// InspectorTable is the table that holds the inspector relation/edge.
	InspectorTable = "buildings"
	// InspectorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InspectorInverseTable = "users"
	// InspectorColumn is the table column denoting the inspector relation/edge.
	InspectorColumn = "inspector_id"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "tasks"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "building_id"
)

// Columns holds all SQL columns for building fields.
var Columns = []string{
	FieldID,
	FieldDistrictID,
	FieldJkhUnitID,
	FieldInspectorID,
	FieldAddress,
	FieldConstructionYear,
	FieldDescription,
	FieldPhoto,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PhotoValidator is a validator for the "photo" field. It is called by the builders before save.
	PhotoValidator func(string) error
)

// OrderOption defines the ordering options for the Building queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDistrictID orders the results by the district_id field.
func ByDistrictID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistrictID, opts...).ToFunc()
}

// ByJkhUnitID orders the results by the jkh_unit_id field.
func ByJkhUnitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJkhUnitID, opts...).ToFunc()
}

// ByInspectorID orders the results by the inspector_id field.
func ByInspectorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInspectorID, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByConstructionYear orders the results by the construction_year field.
func ByConstructionYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConstructionYear, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPhoto orders the results by the photo field.
func ByPhoto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhoto, opts...).ToFunc()
}

// ByJkhUnitField orders the results by jkh_unit field.
func ByJkhUnitField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJkhUnitStep(), sql.OrderByField(field, opts...))
	}
}

// ByDistrictField orders the results by district field.
func ByDistrictField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDistrictStep(), sql.OrderByField(field, opts...))
	}
}

// ByInspectorField orders the results by inspector field.
func ByInspectorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInspectorStep(), sql.OrderByField(field, opts...))
	}
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newJkhUnitStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JkhUnitInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, JkhUnitTable, JkhUnitColumn),
	)
}
func newDistrictStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DistrictInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DistrictTable, DistrictColumn),
	)
}
func newInspectorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InspectorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InspectorTable, InspectorColumn),
	)
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
	)
}
