-- Create "districts" table
CREATE TABLE "public"."districts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "districts_name_key" to table: "districts"
CREATE UNIQUE INDEX "districts_name_key" ON "public"."districts" ("name");
-- Create "jkh_units" table
CREATE TABLE "public"."jkh_units" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "district_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "jkh_units_districts_jkh_units" FOREIGN KEY ("district_id") REFERENCES "public"."districts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "jkh_units_name_key" to table: "jkh_units"
CREATE UNIQUE INDEX "jkh_units_name_key" ON "public"."jkh_units" ("name");
-- Create "roles" table
CREATE TABLE "public"."roles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "roles_name_key" to table: "roles"
CREATE UNIQUE INDEX "roles_name_key" ON "public"."roles" ("name");
-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" character varying NOT NULL,
  "login" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "first_name" character varying NOT NULL,
  "last_name" character varying NOT NULL,
  "role_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_roles_users" FOREIGN KEY ("role_id") REFERENCES "public"."roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
-- Create index "users_login_key" to table: "users"
CREATE UNIQUE INDEX "users_login_key" ON "public"."users" ("login");
-- Create "buildings" table
CREATE TABLE "public"."buildings" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "address" character varying NOT NULL,
  "construction_year" bigint NULL,
  "description" text NULL,
  "photo" character varying NULL,
  "district_id" bigint NOT NULL,
  "jkh_unit_id" bigint NOT NULL,
  "inspector_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "buildings_districts_buildings" FOREIGN KEY ("district_id") REFERENCES "public"."districts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "buildings_jkh_units_buildings" FOREIGN KEY ("jkh_unit_id") REFERENCES "public"."jkh_units" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "buildings_users_assigned_buildings" FOREIGN KEY ("inspector_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "buildings_address_key" to table: "buildings"
CREATE UNIQUE INDEX "buildings_address_key" ON "public"."buildings" ("address");
-- Create "checklists" table
CREATE TABLE "public"."checklists" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "description" text NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "checklists_title_key" to table: "checklists"
CREATE UNIQUE INDEX "checklists_title_key" ON "public"."checklists" ("title");
-- Create "element_catalogs" table
CREATE TABLE "public"."element_catalogs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "category" character varying NULL,
  PRIMARY KEY ("id")
);
-- Create index "element_catalogs_name_key" to table: "element_catalogs"
CREATE UNIQUE INDEX "element_catalogs_name_key" ON "public"."element_catalogs" ("name");
-- Create "checklist_elements" table
CREATE TABLE "public"."checklist_elements" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "order_index" bigint NULL,
  "checklist_id" bigint NOT NULL,
  "element_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "checklist_elements_checklists_elements" FOREIGN KEY ("checklist_id") REFERENCES "public"."checklists" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "checklist_elements_element_catalogs_checklist_elements" FOREIGN KEY ("element_id") REFERENCES "public"."element_catalogs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "tasks" table
CREATE TABLE "public"."tasks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "priority" character varying NOT NULL DEFAULT 'обычный',
  "status" character varying NOT NULL DEFAULT 'New',
  "description" text NULL,
  "scheduled_date" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "building_id" bigint NOT NULL,
  "checklist_id" bigint NOT NULL,
  "inspector_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tasks_buildings_tasks" FOREIGN KEY ("building_id") REFERENCES "public"."buildings" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "tasks_checklists_tasks" FOREIGN KEY ("checklist_id") REFERENCES "public"."checklists" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "tasks_users_inspections" FOREIGN KEY ("inspector_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "inspection_acts" table
CREATE TABLE "public"."inspection_acts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "approved_at" timestamptz NULL,
  "status" character varying NOT NULL DEFAULT 'создан',
  "conclusion" text NULL,
  "document_path" character varying NULL,
  "task_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "inspection_acts_tasks_act" FOREIGN KEY ("task_id") REFERENCES "public"."tasks" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "inspection_acts_task_id_key" to table: "inspection_acts"
CREATE UNIQUE INDEX "inspection_acts_task_id_key" ON "public"."inspection_acts" ("task_id");
-- Create "inspection_results" table
CREATE TABLE "public"."inspection_results" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "condition_status" character varying NOT NULL,
  "comment" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "checklist_element_id" bigint NOT NULL,
  "task_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "inspection_results_checklist_elements_inspection_results" FOREIGN KEY ("checklist_element_id") REFERENCES "public"."checklist_elements" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "inspection_results_tasks_results" FOREIGN KEY ("task_id") REFERENCES "public"."tasks" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "inspector_units" table
CREATE TABLE "public"."inspector_units" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "jkh_unit_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "inspector_units_jkh_units_assigned_inspectors" FOREIGN KEY ("jkh_unit_id") REFERENCES "public"."jkh_units" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "inspector_units_users_assigned_units" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
