// Code generated by ent, DO NOT EDIT.

package inspectionact

import (
	"jkh/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldTaskID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldCreatedAt, v))
}

// ApprovedAt applies equality check predicate on the "approved_at" field. It's identical to ApprovedAtEQ.
func ApprovedAt(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldApprovedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldStatus, v))
}

// Conclusion applies equality check predicate on the "conclusion" field. It's identical to ConclusionEQ.
func Conclusion(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldConclusion, v))
}

// DocumentPath applies equality check predicate on the "document_path" field. It's identical to DocumentPathEQ.
func DocumentPath(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldDocumentPath, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotIn(FieldTaskID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLTE(FieldCreatedAt, v))
}

// ApprovedAtEQ applies the EQ predicate on the "approved_at" field.
func ApprovedAtEQ(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldApprovedAt, v))
}

// ApprovedAtNEQ applies the NEQ predicate on the "approved_at" field.
func ApprovedAtNEQ(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNEQ(FieldApprovedAt, v))
}

// ApprovedAtIn applies the In predicate on the "approved_at" field.
func ApprovedAtIn(vs ...time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIn(FieldApprovedAt, vs...))
}

// ApprovedAtNotIn applies the NotIn predicate on the "approved_at" field.
func ApprovedAtNotIn(vs ...time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotIn(FieldApprovedAt, vs...))
}

// ApprovedAtGT applies the GT predicate on the "approved_at" field.
func ApprovedAtGT(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGT(FieldApprovedAt, v))
}

// ApprovedAtGTE applies the GTE predicate on the "approved_at" field.
func ApprovedAtGTE(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGTE(FieldApprovedAt, v))
}

// ApprovedAtLT applies the LT predicate on the "approved_at" field.
func ApprovedAtLT(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLT(FieldApprovedAt, v))
}

// ApprovedAtLTE applies the LTE predicate on the "approved_at" field.
func ApprovedAtLTE(v time.Time) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLTE(FieldApprovedAt, v))
}

// ApprovedAtIsNil applies the IsNil predicate on the "approved_at" field.
func ApprovedAtIsNil() predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIsNull(FieldApprovedAt))
}

// ApprovedAtNotNil applies the NotNil predicate on the "approved_at" field.
func ApprovedAtNotNil() predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotNull(FieldApprovedAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldContainsFold(FieldStatus, v))
}

// ConclusionEQ applies the EQ predicate on the "conclusion" field.
func ConclusionEQ(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldConclusion, v))
}

// ConclusionNEQ applies the NEQ predicate on the "conclusion" field.
func ConclusionNEQ(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNEQ(FieldConclusion, v))
}

// ConclusionIn applies the In predicate on the "conclusion" field.
func ConclusionIn(vs ...string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIn(FieldConclusion, vs...))
}

// ConclusionNotIn applies the NotIn predicate on the "conclusion" field.
func ConclusionNotIn(vs ...string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotIn(FieldConclusion, vs...))
}

// ConclusionGT applies the GT predicate on the "conclusion" field.
func ConclusionGT(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGT(FieldConclusion, v))
}

// ConclusionGTE applies the GTE predicate on the "conclusion" field.
func ConclusionGTE(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGTE(FieldConclusion, v))
}

// ConclusionLT applies the LT predicate on the "conclusion" field.
func ConclusionLT(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLT(FieldConclusion, v))
}

// ConclusionLTE applies the LTE predicate on the "conclusion" field.
func ConclusionLTE(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLTE(FieldConclusion, v))
}

// ConclusionContains applies the Contains predicate on the "conclusion" field.
func ConclusionContains(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldContains(FieldConclusion, v))
}

// ConclusionHasPrefix applies the HasPrefix predicate on the "conclusion" field.
func ConclusionHasPrefix(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldHasPrefix(FieldConclusion, v))
}

// ConclusionHasSuffix applies the HasSuffix predicate on the "conclusion" field.
func ConclusionHasSuffix(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldHasSuffix(FieldConclusion, v))
}

// ConclusionIsNil applies the IsNil predicate on the "conclusion" field.
func ConclusionIsNil() predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIsNull(FieldConclusion))
}

// ConclusionNotNil applies the NotNil predicate on the "conclusion" field.
func ConclusionNotNil() predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotNull(FieldConclusion))
}

// ConclusionEqualFold applies the EqualFold predicate on the "conclusion" field.
func ConclusionEqualFold(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEqualFold(FieldConclusion, v))
}

// ConclusionContainsFold applies the ContainsFold predicate on the "conclusion" field.
func ConclusionContainsFold(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldContainsFold(FieldConclusion, v))
}

// DocumentPathEQ applies the EQ predicate on the "document_path" field.
func DocumentPathEQ(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEQ(FieldDocumentPath, v))
}

// DocumentPathNEQ applies the NEQ predicate on the "document_path" field.
func DocumentPathNEQ(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNEQ(FieldDocumentPath, v))
}

// DocumentPathIn applies the In predicate on the "document_path" field.
func DocumentPathIn(vs ...string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIn(FieldDocumentPath, vs...))
}

// DocumentPathNotIn applies the NotIn predicate on the "document_path" field.
func DocumentPathNotIn(vs ...string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotIn(FieldDocumentPath, vs...))
}

// DocumentPathGT applies the GT predicate on the "document_path" field.
func DocumentPathGT(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGT(FieldDocumentPath, v))
}

// DocumentPathGTE applies the GTE predicate on the "document_path" field.
func DocumentPathGTE(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldGTE(FieldDocumentPath, v))
}

// DocumentPathLT applies the LT predicate on the "document_path" field.
func DocumentPathLT(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLT(FieldDocumentPath, v))
}

// DocumentPathLTE applies the LTE predicate on the "document_path" field.
func DocumentPathLTE(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldLTE(FieldDocumentPath, v))
}

// DocumentPathContains applies the Contains predicate on the "document_path" field.
func DocumentPathContains(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldContains(FieldDocumentPath, v))
}

// DocumentPathHasPrefix applies the HasPrefix predicate on the "document_path" field.
func DocumentPathHasPrefix(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldHasPrefix(FieldDocumentPath, v))
}

// DocumentPathHasSuffix applies the HasSuffix predicate on the "document_path" field.
func DocumentPathHasSuffix(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldHasSuffix(FieldDocumentPath, v))
}

// DocumentPathIsNil applies the IsNil predicate on the "document_path" field.
func DocumentPathIsNil() predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldIsNull(FieldDocumentPath))
}

// DocumentPathNotNil applies the NotNil predicate on the "document_path" field.
func DocumentPathNotNil() predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldNotNull(FieldDocumentPath))
}

// DocumentPathEqualFold applies the EqualFold predicate on the "document_path" field.
func DocumentPathEqualFold(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldEqualFold(FieldDocumentPath, v))
}

// DocumentPathContainsFold applies the ContainsFold predicate on the "document_path" field.
func DocumentPathContainsFold(v string) predicate.InspectionAct {
	return predicate.InspectionAct(sql.FieldContainsFold(FieldDocumentPath, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.InspectionAct {
	return predicate.InspectionAct(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.InspectionAct {
	return predicate.InspectionAct(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InspectionAct) predicate.InspectionAct {
	return predicate.InspectionAct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InspectionAct) predicate.InspectionAct {
	return predicate.InspectionAct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InspectionAct) predicate.InspectionAct {
	return predicate.InspectionAct(sql.NotPredicates(p))
}
