// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Building is the predicate function for building builders.
type Building func(*sql.Selector)

// Checklist is the predicate function for checklist builders.
type Checklist func(*sql.Selector)

// ChecklistElement is the predicate function for checklistelement builders.
type ChecklistElement func(*sql.Selector)

// District is the predicate function for district builders.
type District func(*sql.Selector)

// ElementCatalog is the predicate function for elementcatalog builders.
type ElementCatalog func(*sql.Selector)

// InspectionAct is the predicate function for inspectionact builders.
type InspectionAct func(*sql.Selector)

// InspectionResult is the predicate function for inspectionresult builders.
type InspectionResult func(*sql.Selector)

// InspectorUnit is the predicate function for inspectorunit builders.
type InspectorUnit func(*sql.Selector)

// JkhUnit is the predicate function for jkhunit builders.
type JkhUnit func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
